### ISSUE TITLE
Regarding sound fingerprinting

### ISSUE THREAD

**Issue by RKavdiya** [AddictedCS/soundfingerprinting#100]
In Sound fingerprinting, why we are making so many database connection in sound fingerprinting? Is it really required? Since it will create too many connection issue.

**Comment by Nekromancer** [comment]
I guess it doesn't really matter, because SQL adapter is obsolete and not suit for any real use case. You should be looking at alternative storages

**Comment by AddictedCS** [comment]
SQL is deprecated.
