### ISSUE TITLE
k-nearest neighbor functions in your code

### ISSUE THREAD

**Issue by postacik** [AddictedCS/soundfingerprinting#102]
Hi,
I have a face recognition library which generates a vector of 128 floating point numbers for a face and I store those values in a database.

In one of my functions, I have to find the best matching face by calculating the eucledian distance (https://en.wikipedia.org/wiki/Euclidean_distance) between the input face and the face data in the database.

In my current implementation I run a query which iterates all the stored face data and returns the one with the minimum distance.

This is a costly function.

Is there any piece of code in your library (k-nearest neighbor?) which I can use to make this function faster?

Thanks in advance :)

**Comment by AddictedCS** [comment]
Hey @postacik,

The code itself contains things that may help you but it's totally wired into the audio recognition, thus would not suggest trying that.

On the other hand, I'd suggest you take a look on existing storages that do provide dimensionality reduction that may very well fit your use case [Falconn Lib](https://falconn-lib.org)  or [NMSLIB](https://github.com/nmslib/nmslib).

**Comment by postacik** [comment]
Thank you very much. I'll look into those. :)
