### ISSUE TITLE
Getting rid of Synchronized attribute on instance members

### ISSUE THREAD

**Issue by AddictedCS** [AddictedCS/soundfingerprinting#105]
Method signatures with `[MethodImpl(MethodImplOptions.Synchronized)]` have to be changed to a more robust multi-threaded access as below.
```csharp
lock(privateLockObject) { /* method body */ }
```
This will prevent deadlocks since `[MethodImpl(MethodImplOptions.Synchronized)]` is just a shortcut to `lock(this) {}`.

More details from [MSDN](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.methodimploptions?redirectedfrom=MSDN&view=netframework-4.7.2)

> Locking on the instance or on the type, as with the Synchronized flag, is not recommended for public types, because code other than your own can take locks on public types and instances. This might cause deadlocks or other synchronization problems.

Search for all classes that contain it and replace accordingly.

**Comment by Nekromancer** [comment]
The only method i found (apart from tests) with this attribute is

```
public static HammingDistanceResultStatistics From(ConcurrentBag<int> truePositivesBag, ConcurrentBag<int> falseNegativesBag, ConcurrentBag<int> falsePositivesBag, double[] percentiles)
```

in file `HammingDistanceResultStatistics`

It's static, so probably lock object would be static as well. 

But i wonder why this method needs to be locked in the first place. It seems like simple pure function. It doesn't depend on anything from the outside. What's your take at it?

**Comment by AddictedCS** [comment]
It is probably a leftover from the past. Since it's static the annotation can be safely removed.

**Comment by Nekromancer** [comment]
I think this annotation from test case is the same - safe to remove: https://github.com/AddictedCS/soundfingerprinting/blob/c4242fdf4c/src/SoundFingerprinting/Utils/TestRunner.cs#L259
