### ISSUE TITLE
How to use sqlmodelservice.I got error

### ISSUE THREAD

**Issue by MahadevanKMKumaran9127** [AddictedCS/soundfingerprinting#110]
I have attached error screen.how to resolve it.
![error00](https://user-images.githubusercontent.com/42438288/48838691-1f00b580-edaf-11e8-9227-54f38e9f73c4.PNG)

**Comment by AddictedCS** [comment]
SoundFingerprinting.SQL is deprecated. Methods from ModelService interface (since v6) are not supported.
