### ISSUE TITLE
How to use the project to detect ads in radio stream files

### ISSUE THREAD

**Issue by programmerREX** [AddictedCS/soundfingerprinting#111]
How can i use it to detect ads in radio stream files

**Comment by Nekromancer** [comment]
You need to have some audio references of ads you want to recognize later. Add them to ModelService. Then all you need to do is to run recognitions on your radio stream files

**Comment by prashuraja** [comment]
I added ad references in model service. But not sure about running recognitions on radio streams which is continuous and real time streams that has no fixed length size.

**Comment by Nekromancer** [comment]
Well, you can dump radio streams using NAudio or ffmpeg every 20-30 seconds and do recognitions on these little chunks. It works decently. There is also a `RealtimeQueryCommand` (https://github.com/AddictedCS/soundfingerprinting/blob/develop/src/SoundFingerprinting/Command/RealtimeQueryCommand.cs) in which you have to provide continous stream of audio samples by `BlockingCollection`

**Comment by programmerREX** [comment]
Thanks very much. I have successfully  got it to detect radios files. The radio files are pre recorded and its able to detect all audios in the radio file which has a duration of about 3 hours. 
I haven’t tried the realtime yet. So I will look at it.

**Comment by timotech** [comment]
>
> Thanks very much. I have successfully got it to detect radios files. The radio files are pre recorded and its able to detect all audios in the radio file which has a duration of about 3 hours. I haven’t tried the realtime yet. So I will look at it.

Hi @programmerREX, please can you provide a sample, how you got the stream of files detection to work?
