### ISSUE TITLE
Sample rate of the given file is not supported Format

### ISSUE THREAD

**Issue by calmeo** [AddictedCS/soundfingerprinting#112]
Hi guys,

> ArgumentException: Sample rate of the given file is not supported Format: SampleRate $1781491047, Channels $24941, BitsPerSample $-9985, Length $6959793. Supported sample rates 5512,8000,11025,16000,22050,44100,48000. Submit a github request if you need a different sample rate to be supported.

I got this problem when I used the link below (which has been converted in to mp3 )
https://www.youtube.com/watch?v=DeumyOzKqgI
Thank you for giving me hand.

**Comment by AddictedCS** [comment]
Hey @calmeo , mp3 files are not supported by `SoundFingerprintingAudioService`. It supports only `wav` files. 
If you want to process mp3s you need to use [SoundFingerprinting.Audio.NAudio](https://www.nuget.org/packages/SoundFingerprinting.Audio.NAudio/) or [SoundFingerprinting.Audio.Bass](https://www.nuget.org/packages/SoundFingerprinting.Audio.Bass/) extensions as described in the README.
