### ISSUE TITLE
Unable  to run project

### ISSUE THREAD

**Issue by ManojkumarHK** [AddictedCS/soundfingerprinting#113]
Once open sln file in  64bit in that i have open SoundFingerprintingTest.cs after built it's showing an error there is no startupproject. Can anyone help its very necessary for me.

**Comment by Nekromancer** [comment]
What are you trying to do exactly? SoundFingerprinting is a library. You need to use it in your application (NuGet is best option here). Everything you need to do that is in readme

**Comment by Furlingbird** [comment]
Dear team
Is there a step by step guide of how to run the program in visual studio?. 
After running Nuget and even GitHub i am still failing to run the project. 

i tried to opening the project then, adding an executable into that project and making it a startup project, i also tried adding  a button to this project and added the 1st code from the Readme File to the project but it underlines the first two lines in the code 


private readonly IModelService modelService = new InMemoryModelService(); // store fingerprints in RAM
private readonly IAudioService audioService = new SoundFingerprintingAudioService(); // default audio library

a friend of mine told me to add the framework as a reference into any project i was running , 

please help as i am a newbie but very interested in this project.

**Comment by Nekromancer** [comment]
There is a very detailed instructions how to add new track to database and run recognition on audio file just here https://github.com/AddictedCS/soundfingerprinting . The only thing you have to do is to download NuGet, add usings to your file and use code from documentation.

**Comment by Furlingbird** [comment]
after adding the nuget to my file i am getting errors when i add the source code from the documentation

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace SoundTest
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
        }


        private readonly IModelService modelService = new InMemoryModelService(); // store fingerprints in RAM
        private readonly IAudioService audioService = new SoundFingerprintingAudioService(); // default audio library

        public void StoreAudioFileFingerprintsInStorageForLaterRetrieval(string pathToAudioFile)
        {
            var track = new TrackInfo("GBBKS1200164", "Skyfall", "Adele", 290d);

            // create fingerprints
            var hashedFingerprints = FingerprintCommandBuilder.Instance
                                        .BuildFingerprintCommand()
                                        .From(pathToAudioFile)
                                        .UsingServices(audioService)
                                        .Hash()
                                        .Result;

            // store hashes in the database for later retrieval
            modelService.Insert(track, hashedFingerprints);
        }

        private void Button_Click(object sender, RoutedEventArgs e)
        {

        }
    }
}


I am adding that code into the new windows form window
sorry if i am asking what appears to be obvious
 
![image](https://user-images.githubusercontent.com/21693225/52522332-95190800-2c8c-11e9-91c8-994a02be6121.png)

**Comment by Nekromancer** [comment]
Look, it's pretty clear that you have no idea what are you doing. Please learn some C# and then come back to use libraries. With this attitude you are just wasting time

**Comment by Furlingbird** [comment]
> Look, it's pretty clear that you have no idea what are you doing. Please learn some C# and then come back to use libraries. With this attitude you are just wasting time

Thanks for the reply, i will read on how to use libraries in c# and see how far i go from there.

**Comment by ManojkumarHK** [comment]
Hi

Few days I posted some doubts after that I gone through you're git document
and I implemented an application. In my application I planning to split
20sec input microphone audio files and comparing with recorded audio where
am using IModelService modelService = new InMemoryModelService(); am
getting result and there's some problem like where am giving  int
secondsToAnalyze = 19; . Is this right way to implement

Thanks.

**Comment by Nekromancer** [comment]
Could you post some code that you are using?

**Comment by AddictedCS** [comment]
Irrelevant.
