### ISSUE TITLE
Microphone matching confidence

### ISSUE THREAD

**Issue by psuresan12** [AddictedCS/soundfingerprinting#116]
I have been trying to match microphone recording against InMemoryModelService.Saved the microphone recording to temp .wav file and passed it to query but unable to get result, even though I was able to play the recorded file in VLC player . However, Able to recognise trimmed version of original file instead of microphone recording.

I am not sure if my below code to sample microphone recording is right ? Has any one tried matching with microphone?

NAudioSoundCaptureService captureService = new NAudioSoundCaptureService();
NAudioWaveFileUtility fileUtility = new NAudioWaveFileUtility();
float[] captureMicrophoneSample = captureService.ReadMonoSamples(5512,10);
fileUtility.WriteSamplesToFile(captureMicrophoneSample,5512,destination);

**Comment by mdmartinezpad** [comment]
Hi @psuresan12 , could you solve it?  thank!
