### ISSUE TITLE
Runtime Interop exception(COMException: Exception from HRESULT: 0xC00D5212)

### ISSUE THREAD

**Issue by psuresan12** [AddictedCS/soundfingerprinting#117]
I was trying to fingerprint .wav file that was saved from microphone, but getting the COMException: Exception from HRESULT: 0xC00D5212 while fingerprinting. Attached .wav file for reference in https://drive.google.com/open?id=1roSP8VWO-1HHT8R7RP6UcBl0TJngyAYd

I was using NAudioService File was recorded with 5512 sample rate for 10 seconds.

**Comment by AddictedCS** [comment]
Can't reproduce.
