### ISSUE TITLE
on Query it hangs

### ISSUE THREAD

**Issue by rionon** [AddictedCS/soundfingerprinting#118]
everything is working but
It gets hanged here:

       **Dim queryResult = QueryCommandBuilder.Instance.BuildQueryCommand.From(queryAudioFile).UsingServices(modelService, audioService).Query.Result**

**Comment by mdmartinezpad** [comment]
I have the same problem too in the same line ,Why?

**Comment by iqunas** [comment]
I am having the same problem too.. Kindly Advise! Thanks

**Comment by iqunas** [comment]
> I have the same problem too in the same line ,Why?
> 
> my code:
> 
> using System;
> using System.Windows.Forms;
> using SoundFingerprinting;
> using SoundFingerprinting.Audio;
> using SoundFingerprinting.Builder;
> using SoundFingerprinting.DAO.Data;
> using SoundFingerprinting.Data;
> using SoundFingerprinting.InMemory;
> 
> namespace WindowsFormsApp3
> {
> public partial class Form1 : Form
> {
> public Form1()
> {
> InitializeComponent();
> }
> 
> ```
>     private readonly IModelService modelService = new InMemoryModelService(); // store fingerprints in RAM
>     private readonly IAudioService audioService = new SoundFingerprintingAudioService(); // default audio library
>             
> 
>     public void StoreAudioFileFingerprintsInStorageForLaterRetrieval(string pathToAudioFile)
>     {
>         var track = new TrackInfo("GBBKS1200164", "Skyfall", "Adele", 290d);
> 
>         // create fingerprints
>         var hashedFingerprints = FingerprintCommandBuilder.Instance
>                                     .BuildFingerprintCommand()
>                                     .From(pathToAudioFile)
>                                     .UsingServices(audioService)
>                                     .Hash()
>                                     .Result;
> 
>         // store hashes in the database for later retrieval
>         modelService.Insert(track, hashedFingerprints);
>         textBox2.Text = modelService.ReadTrackById("GBBKS1200164").Title.ToString();
>     }
> 
>     public TrackData GetBestMatchForSong(string queryAudioFile)
>     {
>         int secondsToAnalyze =10; // number of seconds to analyze from query file
>         int startAtSecond = 0; // start at the begining
> 
>         // query the underlying database for similar audio sub-fingerprints
>         var queryResult = QueryCommandBuilder.Instance.BuildQueryCommand()
>                                              .From(queryAudioFile, secondsToAnalyze, startAtSecond)
>                                             // .UsingServices(modelService, audioService)
>                                              .UsingServices(modelService, audioService)
>                                              .Query()                                                 
>                                              .Result;
> 
>         return queryResult.BestMatch.Track;
>     }
> 
> 
>     private void button1_Click(object sender, EventArgs e)
>     {
>         StoreAudioFileFingerprintsInStorageForLaterRetrieval(@"D:\prueba\original\Skyfall - Adele1.wav");
>         TrackData oTrackData= GetBestMatchForSong(@"D:\prueba\test\Skyfall - Adele1.wav");
>         textBox1.Text = oTrackData.Artist;
>     }
> }
> ```
> }

Have you got any solution ?

**Comment by AddictedCS** [comment]
Since you are updating the UI components you can't just access `Result` from a Task that completes asynchronously. You should take care of tasks current synchronization context when updating the UI with the result generated by an async library. [Here](https://devblogs.microsoft.com/pfxteam/await-and-ui-and-deadlocks-oh-my/) you will find explanations of how to properly use Tasks within an application that updates the UI.

Specifically this line:

> With that in mind, consider this (faulty) reimplementation of button1_Click:

private void button1_Click(object sender, RoutedEventArgs e) 
{ 
    Task<string> s = LoadStringAsync(); 
    textBox1.Text = s.Result; // warning: buggy 
}

There’s an exceedingly good chance that this code will hang your application.  The Task<string>.Result property is strongly typed as a String, and thus it can’t return until it has the valid result string to hand back; in other words, it blocks until the result is available.  We’re inside of button1_Click then blocking for LoadStringAsync to complete, but LoadStringAsync’s implementation depends on being able to post code asynchronously back to the UI to be executed, and the task returned from LoadStringAsync won’t complete until it does.  LoadStringAsync is waiting for button1_Click to complete, and button1_Click is waiting for LoadStringAsync to complete. Deadlock!

You need to make your method `async` and wait for the result with `await` keyword. Do not access `Result` directly if you are using it on UI thread.

**Comment by mdmartinezpad** [comment]
Thank you!..

 My code works with the following changes :

using System;
using System.Threading.Tasks;
using System.Windows.Forms;
using SoundFingerprinting;
using SoundFingerprinting.Audio;
using SoundFingerprinting.Builder;
using SoundFingerprinting.DAO.Data;
using SoundFingerprinting.Data;
using SoundFingerprinting.InMemory;

namespace WindowsFormsApp3
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }


        private readonly IModelService modelService = new InMemoryModelService(); // store fingerprints in RAM
        private readonly IAudioService audioService = new SoundFingerprintingAudioService(); // default audio library
                

        public async  Task StoreAudioFileFingerprintsInStorageForLaterRetrieval(string pathToAudioFile)
        {
            var track = new TrackInfo("GBBKS1200164", "Skyfall", "Adele", 290d);

            // create fingerprints
            var hashedFingerprints = await FingerprintCommandBuilder.Instance
                                        .BuildFingerprintCommand()
                                        .From(pathToAudioFile)
                                        .UsingServices(audioService)
                                        .Hash();
                                        //.Result;

            // store hashes in the database for later retrieval
            modelService.Insert(track, hashedFingerprints);
          // textBox2.Text = modelService.ReadTrackById("GBBKS1200164").Title.ToString();
        }

       // public TrackData GetBestMatchForSong(string queryAudioFile)
        public  async Task<TrackData> GetBestMatchForSong(string queryAudioFile)
        {
            int secondsToAnalyze =10; // number of seconds to analyze from query file
            int startAtSecond = 0; // start at the begining

            // query the underlying database for similar audio sub-fingerprints
            var queryResult = await QueryCommandBuilder.Instance.BuildQueryCommand()
                                                 .From(queryAudioFile, secondsToAnalyze, startAtSecond)
                                                 // .UsingServices(modelService, audioService)
                                                 .UsingServices(modelService, audioService)
                                                 .Query();                                                 
                                                 //.Result;

            // return  Task.FromResult(queryResult.BestMatch.Track);
            return  queryResult.BestMatch.Track;
        }
          

        private async  void button1_Click(object sender, EventArgs e)          
        {           

            await StoreAudioFileFingerprintsInStorageForLaterRetrieval(@"D:\prueba\original\testaudio1.wav");
            TrackData oTrackData = await GetBestMatchForSong(@"D:\prueba\test\testaudio1.wav");
            textBox1.Text = oTrackData.Artist.ToString();  

        }


    }
}

**Comment by rionon** [comment]
Thanks for help, it worked.

But I was using it for speaker recognition, but I think it doesn't find
track even if track slightly differs. Any suggestion?

Thanks

**Comment by AddictedCS** [comment]
Try using `HighPrecisionQueryConfiguration` and `HighPrecisionFingerprintConfiguration` for query and insertion. It will analyze a different spectrum range and depending on your setup may work better.
