### ISSUE TITLE
Ability to decrease minimum queryAudioFile duration restriction?

### ISSUE THREAD

**Issue by pouwelsjochem** [AddictedCS/soundfingerprinting#122]
I seem to have encountered a minimum duration for the queryAudioFile to find any matches.
Is this because of the fingerprintLengthInSeconds which appears to be `8192 / 5512f` (~1,4 seconds)?

Is there a way to decrease this minimum duration? Or are there any other workarounds?

**Comment by AddictedCS** [comment]
In order to create at least 1 fingerprint, the framework needs ~1.4 seconds (actually slightly more ~1.84 seconds for the first fingerprint due to FFT windowing). Getting around this limitation is not trivial. 

Is there any particular reason why you would like to make it smaller than right now?

**Comment by pouwelsjochem** [comment]
Ah alright, I guess 1.84 seconds is a decent duration length for almost all usecases. But I was requested to search for a track with a source query file of just 1 second.

Looking at the code I can understand it is nowhere near trivial to make adjustments, since everything seems to focus on the 5512 sample rate. I found another library for my usecase now though, called 'dejavu' (Python library).
