### ISSUE TITLE
support for .flac files

### ISSUE THREAD

**Issue by JudeAlquiza** [AddictedCS/soundfingerprinting#123]
Hi, I just encountered this error, and I'm not really sure what it means, 

Sample rate of the given file is not supported Format: SampleRate $863379525, Channels $19777, BitsPerSample $50, Length $3384855. Supported sample rates 5512,8000,11025,16000,22050,44100,48000. Submit a github request if you need a different sample rate to be supported.

Initially, I'm using a flac file but later converted the flac file to mp3 format, then I got the error above.
I tried to convert the mp3 file to an mp3 file that has a sample rate of 48000 and also tried it with 44100 but I still get the same error, 

Not sure what I'm doing wrong, just want to know your thoughts on the right approach to convert the files properly.

Thanks!
Jude Alquiza.

**Comment by AddictedCS** [comment]
Default `SoundFingerprintingAudioService` supports only wave file at the input. If you would like to process other formats, consider using below extensions:
- [SoundFingerprinting.Audio.NAudio](https://www.nuget.org/packages/SoundFingerprinting.Audio.NAudio) - replacement for default `SoundFingerprintingAudioService` audio service. Provides support for *.mp3* audio processing. Runs only on Windows as it uses [NAudio](https://github.com/naudio/NAudio) framework for underlying decoding and resampling.
- [SoundFingerprinting.Audio.Bass](https://www.nuget.org/packages/SoundFingerprinting.Audio.Bass) - Bass.Net audio library integration, comes as a replacement for default service. Works faster than the default or NAudio, more accurate resampling, supports multiple audio formats (*.wav*, *.ogg*, *.mp3*, *.flac*). [Bass](http://www.un4seen.com) is free for non-comercial use. Recommended for enterprise users.

**Comment by JudeAlquiza** [comment]
Hi Thanks :) I'm trying to look for documentation on what nuget packages to install, I know SoundFingerprinting.Audio.Bass is one which I can get from nuget but it seems that there's more, I'm also using .NET Core 3.x, not sure if there is a compatible version of SoundFingerprinting.Audio.Bass with .NET Core 3.x, thanks in advance :)
