### ISSUE TITLE
soundfingerprinting dosen't work

### ISSUE THREAD

**Issue by mbonda** [AddictedCS/soundfingerprinting#131]
I made two recordings of the same song from spotify, one of 3 min. and another 1 min, then use s but with null result

**Comment by AddictedCS** [comment]
No details posted. Closing.

**Comment by mbonda** [comment]
I have a problem with some files, i records wav files from computer by naudio, bur then i have a problem to to recognize them. One of the files I send contains the other, but the recognition is negative
https://we.tl/t-ilifKSGbYF
