### ISSUE TITLE
Question: Using RealtimeQuery for the Audio coming from the Mic

### ISSUE THREAD

**Issue by antongit** [AddictedCS/soundfingerprinting#144]
Hello!
Thanks a lot for your project.

I'm trying to do a RealtimeQuery for the samples I'm getting continuously from the Microphone.
Unfortunately I can't find any examples on how to do so.

This is what I'm doing now:
1. Capturing the samples by using NAudio's WasapiCapture
2. Downsampling them to 5512 with WDLResampler

Then, I've seen: 

* https://github.com/AddictedCS/soundfingerprinting/blob/develop/src/SoundFingerprinting/Command/RealtimeQueryCommand.cs
* https://github.com/AddictedCS/soundfingerprinting/blob/4bdc6ca21323c16ca87c87c10fdb6785e91204f7/src/SoundFingerprinting.Tests/Unit/Query/RealtimeQueryCommandTest.cs

But I'm failing to get it work.

My questions are:
* Am I right with my first two steps?
* Where to find a very small example on how to proceed further? Or which part of the RealtimeQueryCommandTest.cs should I try to adapt first?

Thank you!

Best,
Anton

**Comment by AddictedCS** [comment]
You are right with the first 2 points.

> Capturing the samples by using NAudio's WasapiCapture

Can't you just specify via recording arguments that you need audio in 5512Hz format?
This way you will not need to resample it. Avoiding resampling is preferable.

Here is a short gist which explains how to use the realtime command: https://gist.github.com/AddictedCS/8ce2ec2614f1f7ef70b68dbf6b38e331

One thing to keep in mind, `RealtimeCommand` requires 10240 sample chunks at the input.

Let me know if you succeeded.

**Comment by antongit** [comment]
Thank you so much for the answer!
I'll try and report.

**Comment by antongit** [comment]
Hi @AddictedCS,

thank you for your example.
I've succeed to run the lib and match the tracks. Works so good!

At the moment I'm reading samples from the harddrive instead from the mic, but the samples are following the same path I've prepared for the mic: downsampling > collecting into chunks > feeding the ReatimeQuery.

> Can't you just specify via recording arguments that you need audio in 5512Hz format?
This way you will not need to resample it. Avoiding resampling is preferable.

I would like to, but it looks like that it's not possible for my laptop's soundcard or I'm just missing the way how to configure the Wasapi recording in 5512Hz. Do you have any hints maybe?

I have some more questions:

#### Is it possible to match the tracks that are not exactly the same, but similar? 
At the moment, no matter what, as soon as I'm setting the `Threshold Votes` to at least `2` I'm getting perfect matches for the hashed and sampled tracks (when they are the same, and the sampled track is being played and preprocessed in real time), but I'm getting no results at all if the tracks are just slightly different. Setting the `Threshold Votes` to `1` results in very many false positives. The strange thing is, that all the `ResultEntries` in both cases are coming with the same `Confidence` of 0.8. Probably I'm doing something wrong?

#### RealtimeQueryConfiguration param meanings
* What does the `Threshold Votes` mean?
* What does the `Stride` mean?
* Am I right that `LowLatencyFingerprintConfiguration` for the hashing should match the `LowLatency` QueryStride for the `RealtimeQueryConfiguration`?

Excuse me, if I'm asking questions already answered somewhere in the docs or the sourcecode, and I just didn't find it.

Thank you!

Best,
Anton

**Comment by AddictedCS** [comment]
> I would like to, but it looks like that it's not possible for my laptop's soundcard or I'm just missing the way how to configure the Wasapi recording in 5512Hz.

Indeed, certain sound cards do not support this range. It is a hardware limitation.

> Is it possible to match the tracks that are not exactly the same, but similar?

It depends on what do you mean by "similar".
I've posted an article were I outline major reasons why the songs do not match. You can read it [here](https://emysound.com/blog/open-source/2020/06/12/how-audio-fingerprinting-works.html) (section "What prevents successful matches?").

> What does the Threshold Votes mean?

Threshold Votes control how lenient you want the algorithm to behave. Things that you've tried with it match the intended use.

> What does the Stride mean?

The fingerprinted audio is cut at a certain interval (measure in samples). Decreasing the stride increases the number of spectrograms, which in turn increases the chance of a successful match.

> Am I right that LowLatencyFingerprintConfiguration for the hashing should match the LowLatency QueryStride for the RealtimeQueryConfiguration?

Yes, they come in pairs.

**Comment by antongit** [comment]
Thanks a lot for your answers!
I will read the article now.

I guess this issue is closed.

**Comment by timotech** [comment]
Hi @antongit I have gone through this thread and found that you may have what I need to resolve my problem.
The challenge I have is the ability to feed the ReatimeQuery, with source from microphone. 
I have a windows forms project, but I noticed that the matching is not working. I'm suspecting that the RealtimeQuery is not getting fed or called continuously.
Please advice on what to do. Do I need to create a timer to run the RecordMicNAudio function continuously or what do I do, based on the example from this link: https://github.com/AddictedCS/soundfingerprinting/wiki/Realtime-Query-Command
Thanks, expecting your reply
Timotech

**Comment by timotech** [comment]
> Hi @AddictedCS,
> 
> thank you for your example. I've succeed to run the lib and match the tracks. Works so good!
> 
> At the moment I'm reading samples from the harddrive, not from the mic, but the samples are following the same path I've prepared for the mic: downsampling > collecting into chunks > feeding the ReatimeQuery.
> 
> > Can't you just specify via recording arguments that you need audio in 5512Hz format?
> > This way you will not need to resample it. Avoiding resampling is preferable.
> 
> I would like to, but it looks like that it's not possible for my laptop's soundcard or I'm just missing the way how to configure the Wasapi recording in 5512Hz. Do you have any hints maybe?
> 
> I have some more questions:
> 
> #### Is it possible to match the tracks that are not exactly the same, but similar?
> At the moment, no matter what, as soon as I'm setting the `Threshold Votes` to at least `2` I'm getting perfect matches for the hashed and sampled tracks (when they are the same, and the sampled track is being played and preprocessed in real time), but I'm getting no results at all if the tracks are just slightly different. Setting the `Threshold Votes` to `1` results in very many false positives. The strange thing is, that all the `ResultEntries` in both cases are coming with the same `Confidence` of 0.8. Probably I'm doing something wrong?
> 
> #### RealtimeQueryConfiguration param meanings
> * What does the `Threshold Votes` mean?
> * What does the `Stride` mean?
> * Am I right that `LowLatencyFingerprintConfiguration` for the hashing should match the `LowLatency` QueryStride for the `RealtimeQueryConfiguration`?
> 
> Excuse me, if I'm asking questions already answered somewhere in the docs or the sourcecode, and I just didn't find it.
> 
> Thank you!
> 
> Best, Anton

Hi Anton, i'm trying to do exactly what you are doing, but I'm stuck at capturing the samples from the mic. Please can you point me in the right direction on how to do that?
Thanks
Tim
