### ISSUE TITLE
The get_Count method does not contain an implementation.

### ISSUE THREAD

**Issue by mbob001** [AddictedCS/soundfingerprinting#145]
Hi,
I tried to use SoundFingerPrinting with SQL. And I get an error after start program: 'The get_Count method of type SoundFingerprinting.SQL.TrackDao from assembly SoundFingerprinting.SQL, Version = 5.2.2.0, Culture = neutral, PublicKeyToken = null does not contain an implementation.'

Error is after calling constructor:
`private readonly IModelService modelServiceSQL = new SqlModelService();`

I am using SoundFingerPrinting .SQL version 5.22 and SoundFingerPrinting version 7.3.3. (I tried same version 5.2.2) and not working.
Thanks.

**Comment by AddictedCS** [comment]
MSSQL is no longer supported.

Please use SoundFingerprinting.Emy for persistent storage use.

```
docker run -d -v /persistent-dir:/app/data -p 3399:3399 -p 3340:3340 addictedcs/soundfingerprinting.emy:latest
```
