### ISSUE TITLE
Experience with delay

### ISSUE THREAD

**Issue by smxthereisonlyone** [AddictedCS/soundfingerprinting#146]
We'd like to put audio triggers into a video stream and then detect those on iOS & Android to synchronize. Is that possible and with what delay?

**Comment by AddictedCS** [comment]
What kind of triggers? Acoustic of Visual?

**Comment by smxthereisonlyone** [comment]
We'd do 20 minutes of video stream with 20 minutes of audio. The video starts and goes for a few minutes.
Now, imagine a user opens an app that includes sound fingerprinting, then sound fingerprinting starts and we'd like to know the exact timecode of the video. Is that possible?

**Comment by AddictedCS** [comment]
This is achievable.

* You need to fingerprint and store your streaming audio first.
* When the second app starts, fingerprint 10-15 seconds chunks and query fingerprints storage.
* Check the results. If `Confidence` is > 0.5, check `TrackMatchStartsAt`, this should give you the position where the query matched in the fingerprinted stream.
* Seek to `TrackMatchStartsAt` + `QueryLength`. This should sync both apps.
