### ISSUE TITLE
Why is discretecoveragelength greater than querylength

### ISSUE THREAD

**Issue by naren-96** [AddictedCS/soundfingerprinting#148]
Why is discretecoveragelength greater than querylength

querylength=16.418
discretecoveragelength =30.374

**Comment by AddictedCS** [comment]
Can you provide an example with the query and actual track you've used to get these results?

**Comment by naren-96** [comment]
an appendix is the test audio

[sample.zip](https://github.com/AddictedCS/soundfingerprinting/files/4872002/sample.zip)

**Comment by AddictedCS** [comment]
I can't reproduce the issue. 

Below is the test I've used to try and reproduce it.
It passes without issues. You can try and execute it on your environment. 

```csharp
    [TestFixture]
    public class July4thTest
    {
        [Test]
        public async Task ShouldIdentifyCoverage()
        {
            string source = @"/Users/sergiuciumac/Desktop/july_4_bug/SearchSource.wav";
            string searchCorrect = @"/Users/sergiuciumac/Desktop/july_4_bug/SearchTarget_correct.wav";
            string searchIncorrect = @"/Users/sergiuciumac/Desktop/july_4_bug/SearchTarget_incorrect.wav";
            
            var modelService = new InMemoryModelService();
            var audioService = new SoundFingerprintingAudioService();

            var hashes = await GetFingerprints(source, audioService);
            var track = new TrackInfo(Guid.NewGuid().ToString(), string.Empty, string.Empty);
 
            modelService.Insert(track, hashes);

            var queryResult = await GetQueryResult(searchCorrect, modelService, audioService);
            AssertLengths(queryResult);

            var queryResult2 = await GetQueryResult(searchIncorrect, modelService, audioService);
            AssertLengths(queryResult2);
        }

        private static async Task<Hashes> GetFingerprints(string source, SoundFingerprintingAudioService audioService)
        {
            return await FingerprintCommandBuilder.Instance
                .BuildFingerprintCommand()
                .From(source)
                .UsingServices(audioService)
                .Hash();
        }

        private static void AssertLengths(QueryResult queryResult)
        {
            Assert.IsTrue(queryResult.ContainsMatches);
            var resultEntry = queryResult.BestMatch;
            Assert.IsTrue(resultEntry!.DiscreteCoverage < 1);
            Assert.IsTrue(resultEntry.DiscreteCoverageLength < resultEntry.QueryLength);
        }

        private static async Task<QueryResult> GetQueryResult(string query, IModelService modelService, SoundFingerprintingAudioService audioService)
        {
            return await QueryCommandBuilder.Instance
                .BuildQueryCommand()
                .From(query)
                .UsingServices(modelService, audioService)
                .Query();
        }
    }
```

Let me know if it fails.

**Comment by naren-96** [comment]
There was an error in the naming of three files in my attachment。I want to  serach  SearchSource.wav  from SearchTarget_correct.wav and SearchTarget_incorrect.wav。Search result of SearchTarget_correct.wav is correct。Search result of SearchTarget_incorrect.wav is incorrect。That can reproduce the issue。

**Comment by naren-96** [comment]
My english is not good。

**Comment by naren-96** [comment]
The following code reproduces the issue;

[TestFixture]
    public class July4thTest
    {
        [Test]
        public async Task ShouldIdentifyCoverage()
        {
            string source = @"/Users/sergiuciumac/Desktop/july_4_bug/SearchSource.wav";
            string searchCorrect = @"/Users/sergiuciumac/Desktop/july_4_bug/SearchTarget_correct.wav";
            string searchIncorrect = @"/Users/sergiuciumac/Desktop/july_4_bug/SearchTarget_incorrect.wav";

            var modelService = new InMemoryModelService();
            var modelService2 = new InMemoryModelService();
            var audioService = new SoundFingerprintingAudioService();

            var hashes = await GetFingerprints(searchCorrect, audioService);
            var track = new TrackInfo(Guid.NewGuid().ToString(), string.Empty, string.Empty);

            modelService.Insert(track, hashes);

            var queryResult = await GetQueryResult(source, modelService, audioService);
            AssertLengths(queryResult);

            var hashes2 = await GetFingerprints(searchIncorrect, audioService);
            var track2 = new TrackInfo(Guid.NewGuid().ToString(), string.Empty, string.Empty);

            modelService2.Insert(track2, hashes2);

            

            var queryResult2 = await GetQueryResult(source, modelService2, audioService);
            AssertLengths(queryResult2);
        }

        private static async Task<Hashes> GetFingerprints(string source, SoundFingerprintingAudioService audioService)
        {
            return await FingerprintCommandBuilder.Instance
                .BuildFingerprintCommand()
                .From(source)
                .UsingServices(audioService)
                .Hash();
        }

        private static void AssertLengths(QueryResult queryResult)
        {


            Assert.IsTrue(queryResult.ContainsMatches);
            var entries = queryResult.ResultEntries.OrderBy(entry => entry.QueryMatchStartsAt).ToList();
            foreach(ResultEntry myResultEntry in entries){
                Assert.IsTrue(myResultEntry!.DiscreteCoverage < 1);
                Assert.IsTrue(myResultEntry.DiscreteCoverageLength < myResultEntry.QueryLength);
            }
        }

        private static async Task<QueryResult> GetQueryResult(string query, IModelService modelService, SoundFingerprintingAudioService audioService)
        {
            return await QueryCommandBuilder.Instance
                .BuildQueryCommand()
                .From(query)
                .WithQueryConfig(
                    config =>
                    {
                        config.AllowMultipleMatchesOfTheSameTrackInQuery = true;
                        return config;
                    }
                )
                .UsingServices(modelService, audioService)
                .Query();
        }
    }

**Comment by naren-96** [comment]
The following code can reproduce the issue.
[TestFixture]
    public class July4thTest
    {
        [Test]
        public async Task ShouldIdentifyCoverage()
        {
            string source = @"/Users/sergiuciumac/Desktop/july_4_bug/SearchSource.wav";
            string searchCorrect = @"/Users/sergiuciumac/Desktop/july_4_bug/SearchTarget_correct.wav";
            string searchIncorrect = @"/Users/sergiuciumac/Desktop/july_4_bug/SearchTarget_incorrect.wav";

            var modelService = new InMemoryModelService();
            var modelService2 = new InMemoryModelService();
            var audioService = new SoundFingerprintingAudioService();

            var hashes = await GetFingerprints(searchCorrect, audioService);
            var track = new TrackInfo(Guid.NewGuid().ToString(), string.Empty, string.Empty);
            modelService.Insert(track, hashes);
            var queryResult = await GetQueryResult(source, modelService, audioService);
            AssertLengths(queryResult);

            var hashes2 = await GetFingerprints(searchIncorrect, audioService);
            var track2 = new TrackInfo(Guid.NewGuid().ToString(), string.Empty, string.Empty);
            modelService2.Insert(track2, hashes2);          
            var queryResult2 = await GetQueryResult(source, modelService2, audioService);
            AssertLengths(queryResult2);
        }

        private static async Task<Hashes> GetFingerprints(string source, SoundFingerprintingAudioService audioService)
        {
            return await FingerprintCommandBuilder.Instance
                .BuildFingerprintCommand()
                .From(source)
                .UsingServices(audioService)
                .Hash();
        }

        private static void AssertLengths(QueryResult queryResult)
        {
            Assert.IsTrue(queryResult.ContainsMatches);
            var entries = queryResult.ResultEntries.OrderBy(entry => entry.QueryMatchStartsAt).ToList();
            foreach(ResultEntry myResultEntry in entries){
                Assert.IsTrue(myResultEntry!.DiscreteCoverage < 1);
                Assert.IsTrue(myResultEntry.DiscreteCoverageLength < myResultEntry.QueryLength);
            }
        }

        private static async Task<QueryResult> GetQueryResult(string query, IModelService modelService, SoundFingerprintingAudioService audioService)
        {
            return await QueryCommandBuilder.Instance
                .BuildQueryCommand().From(query)
                .WithQueryConfig(
                    config =>
                    {
                        config.AllowMultipleMatchesOfTheSameTrackInQuery = true;
                        return config;
                    }
                ).UsingServices(modelService, audioService).Query();
        }
    }

**Comment by AddictedCS** [comment]
Hi @naren-96,

You have correctly specified `AllowMultipleMatchesOfTheSameTrackInQuery` to `true` because your tracks contain two matches. Even more so, these two matches are consecutive.

```
time:           
track:    xxxxx
query:0000xxxxx0xxxxx0000
```

This is the most extreme case of identifying multiple matches in a query. In order for the algorithm to be able to identify a new starting match, your cut of the source has to be more precise. Now, it contains 2 additionals seconds which prevent the algorithm to find a new match, instead of treating it like a gap.

Attached is a more precise cut of the same source, which will not generate gaps, and identify 2 matches in the track.

[more_precise_cut2.zip](https://github.com/AddictedCS/soundfingerprinting/files/4874658/more_precise_cut2.zip)

**Comment by naren-96** [comment]
Interestingly, why do two different results appear in a similar situation in two audio?

**Comment by AddictedCS** [comment]
This is related to how precise the algorithm aligns the sequences. It is a randomized process that tries to identify the exact start and end of the match. In one of the sequences (the correct one), the alignment of the first match is less precise which helps in identifying two different matches, since it passes a threshold set for the maximum gap.

That's why it is so important to have a precise cut for two consecutive matches to be identified separately.
You can take a look at [ShouldIdentifyConsecutiveRepeatingSequencesInTrack][query-command], to get an idea of how the same sequence gets identified in a synthetic test.

[query-command]: https://github.com/AddictedCS/soundfingerprinting/blob/develop/src/SoundFingerprinting.Tests/Unit/Query/QueryCommandTest.cs

**Comment by naren-96** [comment]
OK, I'll make the editing more accurate. This problem is really rare in the test. Two of the more than 600 samples I used have had this problem. Another clip is similar. Thank you very much.

Please forgive me for my poor English. The translation machine may be a little strange.
