### ISSUE TITLE
Unable to read certain WAV files

### ISSUE THREAD

**Issue by asherpatience1** [AddictedCS/soundfingerprinting#154]
**Describe the bug**

SoundFingerprinting is finding an exception while trying to read a WAV file.

I have opened the WAV file with other software (http://www.headbands.com/gspot/v26x/index.htm) to interrogate it's structure and everything appears to be fine.  It also plays fine on all media players I tried.

However, I wrote a BinaryReader class to examine the contents and it appears not to align with standard WAV/RIFF file specification (https://www.aelius.com/njh/wavemetatools/doc/riffmci.pdf).

**To Reproduce**

Attempt to generate fingerprints for the file I've linked:
https://drive.google.com/file/d/1VMdP-swpdLlKB09KgYk8M9cE4XKhqAxN/view?usp=sharing

**Expected behavior**

Fingerprints are generated

**Screenshots**

![image](https://user-images.githubusercontent.com/53590460/98438157-efbded00-211a-11eb-8191-f4b25e02fa12.png)
![image](https://user-images.githubusercontent.com/53590460/98438161-fd737280-211a-11eb-8d15-ae93cfa273af.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by AddictedCS** [comment]
Please use `FFmpegAudioService` available in `SoundFingerprinting.Emy`, it will be able to downsample the files correctly.
Installation details here: https://github.com/AddictedCS/soundfingerprinting/wiki/Supported-Audio-Formats
