### ISSUE TITLE
Adjusting configuration

### ISSUE THREAD

**Issue by chrowe** [AddictedCS/soundfingerprinting#157]
**Describe the bug**
Looking for documentation on how to adjust the configuration for Insert and Query.

**To Reproduce**
I am looking at https://emysound.com/docs/basics and I don't see any documentation on how to change `Stride` or `FrequencyRange` on Insert or `Stride`, `ThresholdVotes`, `AllowMultipleMatchesOfTheSameTrackInQuery`, `FrequencyRange`, or `RelativeTo` on Query.

Additionally, I don't see any description of what the `minCoverage` or `minConfidence` options do.

I am using **curl** but I am not sure if that makes a difference in this case.

Thanks for any help.

**Comment by AddictedCS** [comment]
There is ongoing work on improving documentation now. In the upcoming weeks there is going to be a new released published related to that. I will comment on this thread once it is available.

**Comment by chrowe** [comment]
Thanks,

If I can help test the docs, let me know.

So far the only other issue I have run into is how to store the database in a persistent way using Docker
`docker run -p 3399:3399 -p 3340:3340 addictedcs/soundfingerprinting.emy`

**Comment by AddictedCS** [comment]
In order to store the fingerprints into a folder outside of the Docker container, just map a folder on your disk to `/app/data`.
Example:
```
docker run -d -v /local-disk-dir:/app/data -p 3399:3399 -p 3340:3340 addictedcs/soundfingerprinting.emy
```
Next time you run a different container with Emy you can remap the same local folder to `/app/data` and it will load the fingerprints back.

**Comment by AddictedCS** [comment]
New documentation portal for Emy storage is available here: https://emysound.readme.io/reference
