### ISSUE TITLE
EmySound on MacOS X

### ISSUE THREAD

**Issue by demobiel** [AddictedCS/soundfingerprinting#162]
Hi,

not sure if this is the correct place to ask this question. I am trying to run EmySound on Mac OS X with Docker. The only thing I had to change was the path to the persistent directory.

`docker run -d -v /Users/Admin/docker/persistent-dir:/app/data -p 3399:3399 -p 3340:3340 addictedcs/soundfingerprinting.emy:latest`

The folder exists, docker runs fine, and I can access the GUI via my browser.

However when I try to upload a song via the JSON API for fingerprinting I always get error 500, with an empty response body. 
Other endpoints seem to work fine. 
I tried to ssh into the Docker file to see if I could find some logs, but the only log file I can find is nlog.log, and there I don't see any errors appearing when I do a request.

Can you point me out where to start looking for the error? My first guess would be file permissions or something like that, but I am not sure.

The query I try to run is (taken from your blog):
`curl -v 'http://localhost:3340/api/v1/tracks' \
    -H 'Authorization: Basic Admin:' \
    -F 'track.id=test-id' \
    -F 'track.title=test-title' \
    -F 'track.artist=test-artist' \
    -F 'track.metaFields[test-meta-key]=test-meta-value' \
    -F 'track.mediaType=Audio,Video' \
    -F 'insertOriginalPoints=true' \
    -F 'file=@song1.mp3'`

Where I know for sure "song1.mp3" exists. I also tried with a encoded url to an existing mp3 file.

Kind regards

Andries

**Comment by AddictedCS** [comment]
Hey @demobiel,

Can you send me the `song1.mp3` file?

**Comment by demobiel** [comment]
hi,

of course :)

I uploaded it to wetransfer: https://wetransfer.com/downloads/843ee51ca11adbfec8b1fea61f6b75a720210125102054/f7eb5d502499d50e9cf7c05530e07bcf20210125102134/609a6a

I will try to test with other file as well.

Kind regards,

Andries

**Comment by demobiel** [comment]
I tried with another song, but it is the same problem. This is the output (if this might help) of the CURL command:

`curl -v 'http://localhost:3340/api/v1/tracks' \
    -H 'Authorization: Basic Admin:' \
    -F 'track.id=test-id' \
    -F 'track.title=test-title' \
    -F 'track.artist=test-artist' \
    -F 'track.metaFields[test-meta-key]=test-meta-value' \
    -F 'track.mediaType=Audio,Video' \
    -F 'insertOriginalPoints=true' \
    -F 'file=@song2.mp3'
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 3340 (#0)
> POST /api/v1/tracks HTTP/1.1
> Host: localhost:3340
> User-Agent: curl/7.54.0
> Accept: */*
> Authorization: Basic Admin:
> Content-Length: 3789271
> Expect: 100-continue
> Content-Type: multipart/form-data; boundary=------------------------eba1d0671e57b56e
> 
< HTTP/1.1 100 Continue
< HTTP/1.1 500 Internal Server Error
< Date: Mon, 25 Jan 2021 10:55:04 GMT
< Server: Kestrel
< Content-Length: 0
* HTTP error before end of send, stop sending
< 
* Closing connection 0`

**Comment by AddictedCS** [comment]
I've reproduced the issue. Will provide a fix later today.

**Comment by demobiel** [comment]
wow, thanks :)

**Comment by AddictedCS** [comment]
The issue has been fixed in `7.5.5-community`.
You can try it with latest docker image:
```bash
docker run -v /local:/app/data -p 3399:3399 -p 3340:3340 addictedcs/soundfingerprinting.emy:latest
```
Please note I've updated the cUrl interface so now in order to specify track details there is no need to prefix the parameters with *track* name. Below is an example of how to insert a track via cURL:
```bash
curl -v 'http://localhost:3340/api/v1/tracks' -H 'Authorization: Basic Admin:' -F 'id=test-id' -F 'title=test-title' -F 'artist=test-artist' -F 'metaFields[test-meta-key]=test-meta-value' -F 'mediaType=Audio' -F 'file=@song1.mp3'
```

Let me know if it fixed the problem.

**Comment by demobiel** [comment]
Thanks for the quick fix, it works now, I can post a file and I see it appearing in the backoffice!

Now I need to try to do a query that returns a result, as at the moment I always get an empty array back.

**Comment by AddictedCS** [comment]
What is the cURL command you are posting?

**Comment by demobiel** [comment]
hi,

well I now try this one:

`curl 'http://localhost:3340/api/v1/query' \
    -H 'Authorization: Basic Admin:' \
    -F 'file=@query.mp3' \
    -F 'mediaType=Audio,Video' \
    -F 'minCoverage=0.1' 
    -F 'registerMatches'=true
`

where query.mp3 is a snippet of 10 seconds of song1.mp3

**Comment by AddictedCS** [comment]
Can you send me the query.mp3 please?

**Comment by demobiel** [comment]
of course :)

however I also read this in the docs:

`Emy provides a backoffice interface which you can access on port :3340. In order to insert and query Emy server please install SoundFingerprinting.Emy NuGet package.`

as I am on a Mac, I can't install this, is this required when I query it via the API?

you can download the query.mp3 here:
https://wetransfer.com/downloads/a4d82bcc5ac4768db51c9426bd59812b20210125164114/d7f0a40ec5650402e6bbc005a8e31c0b20210125164136/ef4939

**Comment by demobiel** [comment]
yesss this works so nice :)
