### ISSUE TITLE
Question: How to use microphone as streaming source?

### ISSUE THREAD

**Issue by amirh484fj** [AddictedCS/soundfingerprinting#163]
Hi,
Could you please guide me how can I use microphone as streaming source like Shazam or BeatFind?
As you know it seems these softwares listen to the music as long as needed to identify the music through the microphone and announce it whenever the amount of incoming music is enough that they can answer.
Is there any sample code or documantation that helps?

**Comment by Didyman1983** [comment]
Hello, here I use NAudio with WaveIn(). Let me know

**Comment by supermanneo** [comment]
I also want to ask this question.

**Comment by timotech** [comment]
How come there is no windows forms application sample for this great library. I'm having issues making it to work on windows forms
