### ISSUE TITLE
Error using Documentation ReadMe to Query matches

### ISSUE THREAD

**Issue by jeffward01** [AddictedCS/soundfingerprinting#169]
**Describe the bug**
I have uploaded songs and videos using the Emy GUI. These worked fine during the upload process using the GUI.  Although when using code I received the error (unsupported sample bitrate found)... But success, I was able to upload the videos and music files using the GUI.

**Successful upload using the GUI of video and music files**
![image](https://user-images.githubusercontent.com/12589359/128159577-28520dba-01ae-4cf3-9712-998fb3a2af1c.png)

When I go to look for matches, I receive an error using .NET code which I have opened a [ticket for here](https://github.com/AddictedCS/soundfingerprinting/issues/168#issuecomment-892499824).  I have now tried to use the GUI and receive this error:

**Music File**
![image](https://user-images.githubusercontent.com/12589359/128159368-eb99bb83-f1a5-4620-be60-2ea415579ee6.png)

**Video**
![image](https://user-images.githubusercontent.com/12589359/128159028-f275e158-f620-4265-9c17-a5a91a865910.png)

I have uploaded the exact same file in one scenario and received this error. In another scenario I have merged two videos together and received the same error.

Does anyone know why I am getting this error? @AddictedCS 

Thanks!

**Comment by AddictedCS** [comment]
Hey @jeffward01 ,

Can you send me the file please which triggers this error?

**Comment by AddictedCS** [comment]
Also if you are trying to use .NET code to issue query/insert commands, please use `FFmpegAudioService` when generating insert/query commands. By default it uses SoundFingerprintingAudioService hence you got the error related to the bitrate.

You can find the usage examples here: https://emysound.readme.io/reference/query-1

**Comment by jeffward01** [comment]
> Hey @jeffward01 ,
> 
> Can you send me the file please which triggers this error?

Here are the files: https://ufile.io/dkwe9ypx

Thanks for giving it a look I appreciate it!

Feel free to close the ticket if all is done here

**Comment by AddictedCS** [comment]
I've replied in #168 regarding the issue you've been experiencing. 
Will close this issue to remove confusion.
