### ISSUE TITLE
[Not a bug] [Example Requested] Is there a .NET example of how to work with Real Time data?

### ISSUE THREAD

**Issue by jeffward01** [AddictedCS/soundfingerprinting#170]
Hello!

I have been reviewing the code base and also documentation to learn how to work with real time data.  I see in the documentation I can work with [JSON queries](https://emysound.readme.io/reference/post_api-v1-streams).  I would prefer to work with .NET library itself.

I was reviewing the .NET code, and I found [this class (QueryCommandBuilder)](https://github.com/AddictedCS/soundfingerprinting/blob/33683df823235987f6228e001bbeeebed65b50f0/src/SoundFingerprinting/Builder/QueryCommandBuilder.cs).  I was digging into the code and I saw that the parameters for one of the commands was "AudioSample".  Then I began to dig to see how I can query AudioSamples.  

Ultimately I was not successful at discovering how to query and perform the commands:

Get registered streams.
GET
Register a new stream for monitoring.
POST
Get stream by ID.
GET
Removes a stream from monitoring.

from the .NET code.

Is there an example I missed that demonstrates this? I searched pretty deep before I opened an issue for this.

-------

**Update 1**
I did find this code here ([from this issue](https://github.com/AddictedCS/soundfingerprinting/issues/144#issuecomment-639313883)):

https://gist.github.com/AddictedCS/8ce2ec2614f1f7ef70b68dbf6b38e331

I am unclear on how to locate and work with:

`  var collection = new BlockingCollection<AudioSamples>();`

Ultimately I do not know where the source comes from. It is very clear in the JSON commands, but in .NET commands it is less clear.

**Update 2**

I also found this reply in an issue: https://github.com/AddictedCS/soundfingerprinting/issues/111#issuecomment-488934919, it is referring to using the NAudioService  or FFmpegAudioService.

Maybe I am tired and not able to properly read the code that was refrenced, is it possible that you provide a very simple snippet of reading a real time LiveStream mock URL?

---------

**GOAL**
Ideally, I want to register a RTMP or similar livestream URL and be able to ingest that.

Thanks for the help!

**Comment by AddictedCS** [comment]
Hey @jeffward01,

In order to start querying realtime source like livestream URL or RTMP you can use the following snippet as an example:
```csharp
string streamUrl = "https://tunein.streamguys1.com/cnn-new";
var audioService = new FFmpegAudioService();
var asyncSource = audioService.ReadMonoSamplesFromSource(streamUrl, 5512, 60, CancellationToken.None);
var credentials = new Credentials("<INSERT TENANT>","<INSERT KEY>");
var modelService = EmyModelService.NewInstance("api.emysound.com", 3399, credentials);
QueryCommandBuilder
        .Instance
        .BuildRealtimeQueryCommand()
        .From(asyncSource)
        .WithRealtimeQueryConfig(config => {

            config.PermittedGap = 2d;
            config.ResultEntryFilter = new TrackRelativeCoverageLengthEntryFilter(0.2, waitTillCompletion: true);
            config.SuccessCallback = entry =>
            {
                Logger.Info($"[{clientId}] Match identified {entry.MatchedAt:O}. Track {entry.Track.Id} {entry.Track.Title} Coverage {entry.Coverage.TrackCoverageWithPermittedGapsLength:0.00} sec, {entry.TrackRelativeCoverage:0.000}");
                modelService.RegisterMatches(new[] {new AVQueryMatch(Guid.NewGuid().ToString(), streamId, entry.ToQueryMatch(), null)}, new Dictionary<string, string>());
            };

            config.DidNotPassFilterCallback = entry =>
            {
                Logger.Debug($"[{clientId}] did not pass filter {entry.MatchedAt:O}. Track {entry.Track.Id} {entry.Track.Title} Coverage {entry.Coverage.TrackCoverageWithPermittedGapsLength:0.00} sec, {entry.TrackRelativeCoverage:0.000}.");
            };

            config.ErrorCallback = (exception, hashes) =>
            {
                Logger.Error(exception, $"[{clientId}] an exception occured while querying {streamUrl} with hashes of length {hashes.DurationInSeconds} sec");
            };

            return config;
        })
        .Intercept(hashes =>
        {
            // since we are intercepting hashes here, this means that stream is healthy
            Logger.Info($"[{clientId}] query to be issued {hashes.DurationInSeconds:0.00} secs, stream ID {stream.StreamId} for time {hashes.RelativeTo:u}");
        })
        .UsingServices(modelService)
        .Query(source.Token)
        .ContinueWith(async task =>
        {
            DisposeEmyInterfacesOnStreamEnd(modelService);
            
        }, CancellationToken.None);
            
```

**Comment by duki22** [comment]
What does permittedGap stand for ?

**Comment by AddictedCS** [comment]
Hey @duki22, permittedGap is a parameter that tells the framework to ignore detected gaps of the given length.
So, if you set it to 5 seconds, any 5 seconds gap between query and track will not be acknowledged in the `Coverage` object of the `ResultEntry` class.
