### ISSUE TITLE
AudioSamples Format

### ISSUE THREAD

**Issue by Galileon** [AddictedCS/soundfingerprinting#171]
Hi,

I have tried to use raw audio samples as source, have tried PCM 16,24,32 bit, little/bigendian etc. but seems no any combination want to work.

```
  var filestream = System.IO.File.ReadAllBytes(@"D:\sampleData.raw");

            var queryResult = await QueryCommandBuilder.Instance.BuildQueryCommand()
                                     .From(new AudioSamples(SamplesConverter.GetFloatSamplesFromByte(((filestream.Length - 1) / 4) * 4, filestream), "NET",8000))
                                     .UsingServices(GetOrInitModelService(repositoryName), _audioService)
                                     .Query();

```

Any advice is welcome :)

**Comment by AddictedCS** [comment]
If you are storing audio in wave format (raw extension), you can just specify the path to audio file in the `From` method.
No need to pass `AudioSamples`.
If you still need to pass `AudioSamples` as the input to `From` method, make sure to downsample the audio to 5512 Hz before doing that.
