### ISSUE TITLE
Query against a subset of the tracks (filtering the tracks)

### ISSUE THREAD

**Issue by raxIsBlur** [AddictedCS/soundfingerprinting#175]
Hello,

First of all this is more of a question than an issue and also thank you (to the creator) for the library! 
Apologies if its the wrong place to do so, do let me know where I can post this.

I'm wondering if its possible to run the query against a subset of the tracks that are stored in Emy? 
Is there a way to filter the tracks stored based on a prefix in the name or id, and use the filtered tracks for the query?

I guess what I'm hoping to achieve is that based on a prefix of an audio file for the query, I would want to filter the tracks that are stored in Emy that matches the same prefix in the Id or Title to be used for the querying process. 

Example of the file names
query file - Rock_Query_XXX
track files in Emy - Rock_Track_AAA, Rock_Track_BBB and etc.

**Comment by AddictedCS** [comment]
Hey @raxIsBlur it is possible.
When you insert tracks you can specify key-values meta fields in the MetaFields property.
As an example:
```csharp
var t1 = new TrackInfo("1", "Rock Query", "", new Dictionary<string, string>{{ "country", "AAA" }});
var t2 = new TrackInfo("2", "Rock Query", "", new Dictionary<string, string>{{ "country", "BBB" }});
// create fingerprints and insert both t1 and t2
```
During query time you can filter only those tracks that contain certain meta fields. As an example:
```csharp
QueryCommandBuilder.Instance.BuildQueryCommand()
                  .From("file")
                  .WithQueryConfig(config =>
                  {
                        config.YesMetaFieldsFilters = new Dictionary<string, string> {{"country", "AAA"}};
                        return config;
                  })
                  .UsingServices(modelService)
                  .Query();
```

Above query will ignore track t2 since it's country meta fields is set to BBB.
Similarly you can use `NoMetaFieldsFilters`, which will works as logical negation (MUST_NOT).

**Comment by raxIsBlur** [comment]
@AddictedCS Great! That's amazing 👍 
Thank you very much for providing the sample as well.
