### ISSUE TITLE
Unable to load DLL avformat.58

### ISSUE THREAD

**Issue by AmirHossein484** [AddictedCS/soundfingerprinting#177]
**The bug**

Hello,
I've created a docker linux container using the 7.17 version and asp.net core web api, I had a hard time fixing the ffmpeg recognition problem by installing it globally in the image when it was created (unfortunately this problem could not be solved just by setting ffmpeg.RootPath)

Part of my Dockerfile:

FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
RUN apt update
RUN apt-get install ffmpeg -y
WORKDIR /app
EXPOSE 80

everything was going well but after upgrading to version 8, Whatever I do, even though ffmpeg is installed globally in my linux image, and yet I put the ffmpeg files in a folder and set the path, I still face with "Unable to load DLL 'avformat.58 under /app/lib': The specified module could not be found." error.

`ffmpeg.RootPath = $"{Environment.CurrentDirectory}/lib";`

**Screenshots**
![Clipboarder 2021 12 27](https://user-images.githubusercontent.com/7824688/147489230-127cf16a-cd8f-4a93-a5db-ba3176a3d531.png)
![Clipboarder 2021 12 27-002](https://user-images.githubusercontent.com/7824688/147489231-0fb987e6-86c4-4080-a9f0-3cd9e64dec24.png)

**Desktop (please complete the following information):**
 - OS: Windows 11, (But I have faced this issue in docker Debian linux container)
 - Visual Studio 2022
 - Browser Microsoft Edge

I have installed latest version of ffmpeg.AutoGen nuget package (v4.4.1.1) but my problem is still there.

**Comment by AddictedCS** [comment]
You don't need to set the FFmpeg path explicitly.
The library is aware of the OS on which you are loading it. 
In this case, `apt-get install ffmpeg` should suffice for the library to find it.
The following paths will be probed: `{"/usr/lib", "/usr/lib/x86_64-linux-gnu", "/usr/lib/aarch64-linux-gnu"};`

**Comment by AmirHossein484** [comment]
Thanks,
