### ISSUE TITLE
Documentation/Users Guide to the Docker Community Edition

### ISSUE THREAD

**Issue by apb2019** [AddictedCS/soundfingerprinting#180]
Hi, sorry if this has been answered already but is there any documentation on how to use the Docker community edition or a beginners guide? The docs I've found all seem to be aimed at programmers using the API directly rather than via the docker webpage so I would appreciate some guidence as to how to use it.
So far I have been able to load some tracks into its database using the webpage "Tracks" option but I can't see how to now test a file against those tracks?  I would assume its the Matches option but as seems to be for free text entry rather than a file picker how do I tell it the file to test?

**Comment by AddictedCS** [comment]
For testing purposes, you can access the Swagger API available at `http://localhost:3340/docs`.
There you will be able to test the `Query` endpoint with a simple file, or media URL.
The JSON credentials to use for the Community Edition API are username: `ADMIN` with an empty password.
