### ISSUE TITLE
Realtime Recongition: trouble matching audio from video sources

### ISSUE THREAD

**Issue by Hamsterland** [AddictedCS/soundfingerprinting#186]
```cs
_ = QueryCommandBuilder.Instance
    .BuildRealtimeQueryCommand()
    .From(url, chunkLength: 5, mediaType)
    .WithRealtimeQueryConfig(config =>
    {
        config.ResultEntryFilter = new TrackMatchLengthEntryFilter(5d);
        config.SuccessCallback = result =>
        {
            if (result.BestMatch is null)
            {
                return;
            }

            matches.Add(result.BestMatch);
            Console.WriteLine($"Found {result.BestMatch.TrackId}");
        };
        config.ErrorCallback = (exception, _) => Console.WriteLine($"An exception occured while querying the data source: {exception.Message}");
        config.RestoredAfterErrorCallback = () => Console.WriteLine("Query connection re-established");
        config.DidNotPassFilterCallback = result => Console.WriteLine($"Found {result.ResultEntries.Count()} matches, but they did not pass result entry filter.");
        return config;
    })
    .InterceptHashes(hashes =>
    {
        // Console.WriteLine($"Querying the source with hashes {hashes} captured at {hashes.RelativeTo:O}");
        return hashes;
    })
    .UsingServices(ModelService, MediaService)
    .Query(cancellationToken);

await Task.Delay(delay, cancellationToken);
```

If I provide a video link like https://openings.moe/video/BambooBlade-OP01-CDVD.mp4 it does not match, even if I set the media type to video.

But it does work for a muxed link like this https://rr4---sn-cu-cime7.googlevideo.com/videoplayback?expire=1649714925&ei=jVJUYuKwN4nQW7r6veAK&ip=2a00%3A23c7%3A8380%3A6501%3Ab055%3A97c2%3A3dc2%3Afddd&id=o-ABiXfJZwcxC2wrtTbrgNkZRBRgl0tMyRdZYzRmkZahAF&itag=22&source=youtube&requiressl=yes&mh=PH&mm=31%2C29&mn=sn-cu-cime7%2Csn-cu-auoz&ms=au%2Crdu&mv=m&mvi=4&pl=44&gcr=gb&initcwndbps=1872500&vprv=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=103.119&lmt=1531887490994884&mt=1649692853&fvip=1&fexp=24001373%2C24007246&c=ANDROID&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRAIgfBmMS6cYZKoUahGkzi0cW-EH_iOr5BKJBay2otfHh8sCIFDL_nDpz7wh2T1zi1Vumg-1oGGsNQnNtuEb3-c4W7CY&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAOAZbC_UrRVv1xXTWKqrQ7hTleha05gn1-L-OhjuVOz-AiB2kk8Qv_ZIIT7qTGriKsPLBaNYkC8iAkDtIPUvru9WNg%3D%3D

**Comment by Hamsterland** [comment]
Yes I am using `IRealtimeMediaService`  with `FfmpegAudioService`

**Comment by Hamsterland** [comment]
Another example.

[Does not work](https://rr5---sn-cu-cime7.googlevideo.com/videoplayback?expire=1649715760&ei=0FVUYsGwNYKyWsb-rPAP&ip=2a00%3A23c7%3A8380%3A6501%3Ab055%3A97c2%3A3dc2%3Afddd&id=o-ADShRuMrmC1sFUw1buZHzHPavRLDaxQq6oJH2_rkFyH7&itag=22&source=youtube&requiressl=yes&mh=UE&mm=31%2C29&mn=sn-cu-cime7%2Csn-cu-auoz&ms=au%2Crdu&mv=m&mvi=5&pl=44&initcwndbps=1753750&vprv=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=91.138&lmt=1523571316229996&mt=1649693821&fvip=9&fexp=24001373%2C24007246&c=ANDROID&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAN1OrW9BUfrNXzejRZtFiYbF5q2AE1eqcYruGTADtVMvAiBfRQGP1YAbqMy6fu0XiRhxCwSC6mqO0965I3H4Vth5BA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgC_wVFbf0h6w5wZLXJG6yfjoXikB9PXo0hS4M63xyhmcCIFy-LUSqd0DjbudkacfHetZBdqhU2jrzr57F-da9Kbdk)

mp4a.40.2
avc1.64001F
943.76 Kbit/s

[Does work](https://rr4---sn-cu-cime7.googlevideo.com/videoplayback?expire=1649715826&ei=ElZUYtzaMJXdmwfkjbuYCw&ip=2a00%3A23c7%3A8380%3A6501%3Ab055%3A97c2%3A3dc2%3Afddd&id=o-AHNGYl0DOVeA7M3icG2kWlEoWHeZQwVmlogaRR3-J7Z9&itag=22&source=youtube&requiressl=yes&mh=PH&mm=31%2C29&mn=sn-cu-cime7%2Csn-cu-auoz&ms=au%2Crdu&mv=m&mvi=4&pl=44&gcr=gb&initcwndbps=1753750&vprv=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=103.119&lmt=1531887490994884&mt=1649693821&fvip=1&fexp=24001373%2C24007246&c=ANDROID&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAK_atnpfe5it-PBGuzFfc4fJhHWQlw3e9pu0VxNS8JS0AiEAom38hBHi17nON3jIjzKrQrT1l43e4DN0Q_-kEI3ZfJA%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAPX-DFYtspHemUVv-DW7igzBoZ2xuJSXkBFiJLrCApvoAiEArD-sLQ4VLvWDvyMpKJmR8ln2cpK-OcIQYFohlsVYZqc%3D)

mp4a.40.2
avc1.64001F
1.56 Mbit/s

**Comment by Hamsterland** [comment]
Couldn’t really figure out what the issue was. I’d really appreciate some help. Gonna stop working on it for today

**Comment by AddictedCS** [comment]
Can you be more explicit? what did you insert, which params have you been using, and what is the source of data.

**Comment by Hamsterland** [comment]
I figured out my issue. I simply was not allowing enough time before I cancelled the real time search. I have another issue that I will make a separate issue for.
