### ISSUE TITLE
Hash crash when  using a wav with various ID3 tags

### ISSUE THREAD

**Issue by GundlackFlorian** [AddictedCS/soundfingerprinting#193]
Hello,

When i use the hash function on a wav that has some ID3 tags it will result in a `Sample rate of the given file is not supported Format: SampleRate`

What tags exactly ?
It depends, i tried on multiple files, after removing tags one by one with dbpoweramp and relaunching each time it worked.
Some are tags generated by DJ Mixing softwares (serator or traktor) some are just "Comment" or "Description" tags.
The DJ Mixing software ones can be very large but i got some crashes even just a few small or empty tags.

I can provide faulty and their working counterpart files if needed (they are most likely copyrighted so no link here of course).

Edit: 
After looking a little bit more closely in the Audio Property tab i noticed that "Contains" lists:
Album Art, ID Tag [LIST & ID3 & BEXT v0]
I removed randomly tags until the BEXT v0 was not showing anymore.
So i guess that this data is not ignored when reading the file.

**Comment by timotech** [comment]
Try changing your audio service from SoundFingerprintingAudioService to either FFmpegAudioService or NAudioService, it should work with wav files that has different samplerates etc
