### ISSUE TITLE
[Question] Sound fingerprint match always a few seconds/milliseconds too early majority of the time

### ISSUE THREAD

**Issue by sezonis** [AddictedCS/soundfingerprinting#196]
With using this basic code here, with no configurations at all, the match sometimes is always a few milliseconds too early or a second earlier with the track in question.

```
var modelService = new InMemoryModelService();
var audioService = new SoundFingerprintingAudioService(); 
var fingerPrint = await FingerprintCommandBuilder.Instance
                    .BuildFingerprintCommand()
                    .From(trackPath)
                    .UsingServices(audioService)
                    .Hash();
modelService.Insert(track, fingerPrint);

var queryResult = await QueryCommandBuilder.Instance.BuildQueryCommand()
                        .From(pathToSoundFile)
                        .UsingServices(modelService, audioService)
                        .Query();

var match = queryResult.ResultEntries.First();
var startsAt = resultEntry.TrackStartsAt;
var endsAt = resultEntry.DiscreteTrackCoverageLength;
```
I was wondering if there was a way to know if there's a small micro buffer within the match that can be taken into account for the match, to ensure the match is directly at the exact millisecond the track starts. The DiscreteTrackCoverageLength however, seems to function correctly. Now I made sure the raw track sample and the track to listen from both had the same qualities. Both the start and length of said track is the same exact soundwave, but the seconds before that the sound/voice is a little bit different. 

Here is an image of both the tracks that the is being fed to the library, side by side ish, circled in red is the couple milliseconds before the track is played. I know the circle is a little bit bigger on the 2nd track, ignore that. Assume the circle is the same size as the top one. Both wavelengths are zoomed in the exact same spec. 

![image](https://user-images.githubusercontent.com/62833193/196377550-0c89d9db-1186-4623-a2b8-5d7988c2d4c5.png)

Here is the track that we are fingerprinting and being trained into the model service, to the library, which is then used to be fingerprinted by the track above 

The circle indicates where the track starts matched with the black circles on the pic above

![image](https://user-images.githubusercontent.com/62833193/196377261-404f9097-9b6b-44db-83ad-eb494f771e5c.png)

I'm just wanting to know if there's something that will help with the slight shift of wave lengths, to get the exact spot where the track plays every time for every track. Right now it sometimes gets around that area where the red circle is, but I want it to get just the black area. I know it might not be possible but any pointers which can help me lead to the right direction would be appreciated

**Comment by xuboot** [comment]
Hello, have you tested, if I have 1 million songs, is the speed slow when users go to match search? How accurate is it?

**Comment by AddictedCS** [comment]
@sezonis The algorithm has a certain level of matched accuracy which cannot be improved due to various non-trivial reasons. A worst-case scenario (under ideal conditions of having the same source/target track as the query) can yield about 500ms of misalignment.

**Comment by sezonis** [comment]
> @sezonis The algorithm has a certain level of matched accuracy which cannot be improved due to various non-trivial reasons. A worst-case scenario (under ideal conditions of having the same source/target track as the query) can yield about 500ms of misalignment.

Fair enough. It's pretty damn accurate I must say, being dead on accurate would have been A+.

**Comment by sezonis** [comment]
> Hello, have you tested, if I have 1 million songs, is the speed slow when users go to match search? How accurate is it?

No idea I don't use a database as I don't need to for my use case.
