### ISSUE TITLE
System.NullReferenceException: 'Object reference not set to an instance of an object.'

### ISSUE THREAD

**Issue by tplsoft** [AddictedCS/soundfingerprinting#203]
details have this stack  info :  at FFmpeg.AutoGen.Abstractions.ffmpeg.av_log_set_callback(av_log_set_callback_callback_func callback)

I copied ffmpeg x64 files but did not work and checked the [issue 200](https://github.com/AddictedCS/soundfingerprinting/issues/200) also did not work for me.

**Comment by AddictedCS** [comment]
What is the FFmpeg version you are using right now?

**Comment by AddictedCS** [comment]
SoundFingerprinting **v8.22.5** added a new path to FFmpeg probing for macOS silicon.
