### ISSUE TITLE
Pitch-shifted tracks identification

### ISSUE THREAD

**Issue by uoziod** [AddictedCS/soundfingerprinting#204]
First of all — thank you for your amazing job! Emy shows amazing results and it's very easy to use.

My question is regarding pitch-shifted tracks. In majority of cases tunes played by DJs in their performances imply pitch-shifted tracks which according to my tests are not being detected at all by the current algorithm.

Is there any way to maybe by paying the price of precision degradation adding a possibility to detect such tracks?

**Comment by AddictedCS** [comment]
A change in pitch will change the spectrogram from which the fingerprints are generated. Once that happens, the algorithm will not match even if you lower the threshold.

I wrote about how audio fingerprinting works [here](https://emysound.com/blog/open-source/2020/06/12/how-audio-fingerprinting-works.html), with a dedicated section of why certain track/query pairs will not match.

The solution is to fingerprint both the original and the pitched changed track.
