### ISSUE TITLE
[Enhancement Request] Compare 2 differing files and return common sections/ranges within them

### ISSUE THREAD

**Issue by jack4455667788** [AddictedCS/soundfingerprinting#206]
This is a re-request of https://github.com/AddictedCS/soundfingerprinting/issues/18 and https://github.com/AddictedCS/soundfingerprinting/issues/159.

The desired functionality is already well described in both of those closed issues.

I've played around with the library and found that this functionality still does not exist, is that correct?

Are there any plans to add it, or any input/ideas on how to achieve the desired result?  

I have an old piece of code that suggests that AllowMultipleMatchesOfTheSameTrackInQuery used to achieve this at some point in the past (though I don't see how), and although the user from issue 18 did create a branch for it - i'm not sure they ever succeeded either.

Thanks in any case!

**Comment by AddictedCS** [comment]
Did you look at https://github.com/AddictedCS/soundfingerprinting/wiki/Interpreting-Query-Results ?

Specifically Coverage object, it contains all the required info you've asked about.

**Comment by jack4455667788** [comment]
Thank you so much for your quick response!

I was fooling around with QueryResult to no avail, and completely overlooked the coverage object (in the LCS namespace, no less!).

Currently I am using the coverage.TrackGaps/QueryGaps to determine the bounds of the likely matching segments and then fingerprinting those sections to get the QueryResult with the confidence values. Is this the "proper" way to do that? In my case I have common content to identify and remove from multiple files, so I fingerprint one entire file, query it against one other file to get the gaps, fingerprint the segments between those gaps, and then query the rest of the files against those.  

Also, is there any way to configure the sensitivity / "fuzziness" of the gap/segment match detection of the coverage?  Is that just done through the permittedgap/stride of the original fingerprint/query? I don't think i really understand what the permitted gap is/does, since I have it set to 0 and gaps between the location (starting time of match) matches in the track and the query are often much greater than that (they do not share the exact same location/timestamp in both files compared). 

In any case, it is working excellently for my purposes (though now I need to figure out how to add video fingerprinting into the mix to make it work even better). Many thanks!

**Comment by AddictedCS** [comment]
| Also, is there any way to configure the sensitivity / "fuzziness" of the gap/segment match detection of the coverage?

You can control the sensitivity of the query using `ThresholdVotes` parameter on QueryConfiguration; the default value is 4, lowering it to 3 will instruct the algorithm to be less precise, increasing recall. 

As to the permitted gap - it instructs the algorithm to ignore gaps of a certain length (default value is 2). Lowering it to 0 makes little sense, as it will start reporting too many tiny gaps with less than one fingerprint (~1.86 sec) in length. 

Closing the issue as the original question was answered.
