### ISSUE TITLE
During fingerprinting, AVHashes returns empty when specifying secondsToProcess and startAtSecond while creating both audio and video fingerprints

### ISSUE THREAD

**Issue by jack4455667788** [AddictedCS/soundfingerprinting#207]
**Describe the bug**
When fingerprinting (haven't tested query yet) both audio and video simultaneously, if you supply secondsToProcess and startsAtSecond paramaters the AVHashes returned is always empty (isEmpty=true).  Fingerprints are returned as expected if only MediaType.Audio or MediaType.Video are specified, but both (MediaType.Audio | MediaType.Video) does not. Based on the time it takes, it seems likely it is doing neither video or audio hashing of any kind, and just returning the empty AVHash.

**To Reproduce**
1. Try to fingerprint a file (containing audio and video) specifying secondsToProcess, startsAtSecond, and "MediaType.Audio | MediaType.Video" paramaters in the .from method of the FingerprintCommandBuilder.Instance.

**Expected behavior**
Returned fingerprint hashes for both video and audio from the timerange specified by secondsToProcess and startsAtSecond, instead of an empty AVHashes containing no fingerprints.

 - OS: Win7
 - IDE: VSCommunity 2017
   Targeting: .Net v4.6.1
   Using nuGet Packages: SoundFingerprinting.8.23.0, SoundFingerprinting.Emy.8.23.23, FFmpeg.AutoGen.Abstractions.6.0.0.2
   Using git build of ffmpeg pre-compiled from here : https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2023-06-21-15-24/ffmpeg-N-111233-g83b3ff741b-win64-gpl-shared.zip

**Comment by AddictedCS** [comment]
Can you please attach a file and provide the exact parameter values for both `secondsToProcess` and `startsAtSecond` so I can reproduce the issue?

**Comment by jack4455667788** [comment]
Here is the sample file (downloaded format #22 with yt-dlp)

yt-dlp -f 22 https://www.youtube.com/watch?v=4sebEgloQEM

secondsToProcess = 10
startsAtSecond = 33

While playing around with it, it does seem that the particular values above are involved in the issue. There were some, like secondsToProcess = 10, and startsAtSecond = 1 which did appear to work.

In my use case, the secondsToProcess and startsAtSecond values are always doubles (many decimals) and are retrieved from previous query result matches. The above is just a contrived example with a sample file.

**Comment by AddictedCS** [comment]
It is fixed in v8.24.0, you will need to upgrade SoundFingerprinting.Emy to fix version.
Also, I suggest you re-index your database if you've used `secondsToProcess` parameter with both `Audio | Video` flags during track insertion.

Link to NuGet package: https://www.nuget.org/packages/SoundFingerprinting.Emy/8.24.0
