### ISSUE TITLE
Can't open a file because of the sample rate

### ISSUE THREAD

**Issue by rgelb** [AddictedCS/soundfingerprinting#208]
I am trying to open a file, but it blows up with 

```
System.ArgumentException: 'Sample rate of the given file is not supported Format: SampleRate $1650422383, Channels $27233, BitsPerSample $29537, Length $1529823. Supported sample rates 5512,8000,11025,16000,22050,44100,48000,96000. Submit a github request if you need a different sample rate to be supported.'
```

I am using the following code (sample from readme.md):

```c#
string referenceFile = @"Assets\d44.mp3";
IAudioService audioService = new SoundFingerprintingAudioService(); // default audio library
var avReferenceHashes = await FingerprintCommandBuilder.Instance
                             .BuildFingerprintCommand()
                             .From(referenceFile)
                             .UsingServices(audioService)
                             .Hash();
```

I specifically saved the file with a sample rate of 44100 (tried both audacity and ffmpeg).  What am I missing?

[d44.zip](https://github.com/AddictedCS/soundfingerprinting/files/12022809/d44.zip)

**Comment by AddictedCS** [comment]
**MP3** files are not supported by `SoundFingerprintingAudioService`, only WAV.
If you want to use it with MP3, then you need to reference `SoundFingerprinting.Emy` and use `FFmpegAudioService` as described in [Audio Services](https://github.com/AddictedCS/soundfingerprinting/wiki/Audio-Services) wiki page.
