### ISSUE TITLE
Library unable to find a match.

### ISSUE THREAD

**Issue by rgelb** [AddictedCS/soundfingerprinting#210]
**Describe the bug**
I used the sample code from the Readme.md file to create this test.  I have a sample reference .wav file (about 2 seconds).  I added this file to the modelService.  Then I played this file multiple times (for about 10 seconds) and recorded it.  I tried to match it but it doesn't seem to find anything.  

I've reproduced the problem in a small solution in [this repository](https://github.com/rgelb/RecognizeThis).  The repository includes the sample files.

Am I going about it the wrong way?

Entire code base:

```csharp
using SoundFingerprinting.Audio;
using SoundFingerprinting.Builder;
using SoundFingerprinting.Data;
using SoundFingerprinting.InMemory;
using SoundFingerprinting;
using SoundFingerprinting.DAO.Data;

string referenceFile = @"assets\ReferenceSound.wav";
string fileToCompare = @"assets\FileToCompare.wav";

var recognizer = new RecognizeFile();
await recognizer.StoreForLaterRetrieval(referenceFile);

TrackData match = await recognizer.GetBestMatchForSong(fileToCompare);

if (match == null) {
    Console.WriteLine("No Matches");
} else {
    Console.WriteLine(match.Id);
}

class RecognizeFile
{
    private readonly IModelService modelService = new InMemoryModelService(); // store fingerprints in RAM
    private readonly IAudioService audioService = new SoundFingerprintingAudioService(); // default audio library

    public async Task StoreForLaterRetrieval(string file) {
        var track = new TrackInfo("GBBKS1200164", "Skyfall", "Adele");

        // create fingerprints
        var avHashes = await FingerprintCommandBuilder.Instance
                                    .BuildFingerprintCommand()
                                    .From(file)
                                    .UsingServices(audioService)
                                    .Hash();

        // store hashes in the database for later retrieval
        modelService.Insert(track, avHashes);
    }

    public async Task<TrackData> GetBestMatchForSong(string file) {
        int secondsToAnalyze = 10; // number of seconds to analyze from query file
        int startAtSecond = 0; // start at the begining

        // query the underlying database for similar audio sub-fingerprints
        var queryResult = await QueryCommandBuilder.Instance.BuildQueryCommand()
                                             .From(file, secondsToAnalyze, startAtSecond)
                                             .UsingServices(modelService, audioService)
                                             .Query();

        return queryResult.BestMatch?.Audio?.Track;
    }
}
```

**Comment by Bloos** [comment]
Same problem here. I think 2 seconds is simply not enough. Nonetheless I'm also having trouble finding matches with 5, 10 and 15 second samples

**Comment by AddictedCS** [comment]
2 seconds is a very short snippet, you are most likely applying the algorithm for a use case that's not applicable here.
For this use case, you can design your bespoke approach to comparing very short spectrograms between themselves.

**Comment by AddictedCS** [comment]
Closing as a duplicate for #201

**Comment by rgelb** [comment]
@AddictedCS Would you have a recommendation for a 3rd party library that does spectrogram comparisons?

**Comment by Bloos** [comment]
I managed to increase my detection rate. The solution was to use Emy's ffmpegaudioservice. The documentation gave the required hint:

`SoundFingerprintingAudioService:  It supports only WAV files at the input. This implementation is known to alias the audio signal during downsampling. Use this implementation only in testing environments`

I highly dislike this solution because Emy is not Open Source and i cannot verify if the applied algorithm is actually the same, but IT was the only solution that have acceptable results
