### ISSUE TITLE
Probably typo error in Jacquard similarity calculation

### ISSUE THREAD

**Issue by kuleshov-aleksei** [AddictedCS/soundfingerprinting#212]
Hello!

 I've noticed bitwise operator `|` is used instead of binary `||` at [SimilarityUtility.cs#L64](https://github.com/AddictedCS/soundfingerprinting/blob/develop/src/SoundFingerprinting/Math/SimilarityUtility.cs#L64). Seems like this is a typo. Also, it prevents short-circuiting.

Is this intended behavior?

**Comment by AddictedCS** [comment]
Yeah it's a typo binary operator should have been used.

**Comment by kuleshov-aleksei** [comment]
Issue has been resolved in PR https://github.com/AddictedCS/soundfingerprinting/pull/213

Thank you for your amazing project!
