### ISSUE TITLE
AddictedCS FFmpeg.AutoGen System.NullReferenceException

### ISSUE THREAD

**Issue by jdesl** [AddictedCS/soundfingerprinting#214]
**Question**

How can I troubleshoot below issue? AddictedCS SoundFingerprinting FFmpeg.AutoGen System.NullReferenceException Seems to be a class override of FFmpeg.

I am attempting to use AddictedCS SoundFingerprinting 
https://github.com/AddictedCS/soundfingerprinting & https://github.com/Ruslan-B/FFmpeg.AutoGen

First after downloading the packages with nuget SoundFingerprinting.emy I got a   NullReferenceException. 
Next  I downloaded & compiled from source to debug SoundFingerprinting  and FFmpeg.AutoGen.

**For some reason FFmpeg.AutoGen.Abstractions keeps giving a NullReferenceException.** 

Visual Studio 2022, project set to X64

**The exception:**

FFmpeg.AutoGen.Abstractions Code line 2906:

_public static AVFormatContext avformat_alloc_context() => vectors.avformat_alloc_context();*_

System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object
  Source=FFmpeg.AutoGen.Abstractions
  StackTrace:
   at FFmpeg.AutoGen.Abstractions.ffmpeg.avformat_alloc_context() in C:\FFmpeg.AutoGen-master\FFmpeg.AutoGen.Abstractions\generated\ffmpeg.functions.facade.g.cs:line 2906

**ffmpeg.exe as recommended version on the correct location**

C:\fingerPrint\ConsoleApp1\ConsoleApp1\bin\x64\Debug\FFmpeg\bin\x64>ffmpeg.exe 

ffmpeg version 4.4.1-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers built with gcc 11.2.0 (Rev1, Built by MSYS2 project)

**Sourcecode**

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using SoundFingerprinting;
using SoundFingerprinting.Builder;
using SoundFingerprinting.Emy;
using FFmpeg.AutoGen.Bindings.DynamicallyLoaded;
using System.IO;

namespace ConsoleApp1
{
    internal class Program
    {
        private readonly IFingerprintCommandBuilder fingerprintCommandBuilder = new FingerprintCommandBuilder();
        static async Task Main(string[] args)
        {
            var current = Environment.CurrentDirectory;
            var probe = Path.Combine("FFmpeg", "bin", Environment.Is64BitProcess ? "x64" : "x86");
            var ffmpegBinaryPath = Path.Combine(current, probe);
            Console.WriteLine(Environment.CurrentDirectory);
            Console.WriteLine($"FFmpeg binaries found in: {ffmpegBinaryPath}");
            DynamicallyLoadedBindings.LibrariesPath = ffmpegBinaryPath;
  
            var audioService = new FFmpegAudioService();
            var hashedFingerprints = await FingerprintCommandBuilder.Instance
                                             .BuildFingerprintCommand()
                                             .From("c:\\temp\\chopin_short2.wav")
                                             .UsingServices(audioService)
                                             .Hash();
        }
    }
}
```

Where do I need to look next? Doesn't this work with a console C# project?

**Comment by AddictedCS** [comment]
It was to contain not the `ffmpeg.exe` file but the DLLs: `avcodec.dll`, `avformat.dll` etc.

**Comment by jdesl** [comment]
Everything points to that, manually added "DynamicallyLoadedBindings.Initialize();" now it works.
Going to reset & restart everything.

![files](https://github.com/AddictedCS/soundfingerprinting/assets/62758553/65b9f3a3-aaea-465f-be9e-dbb067480f2f)

```
      var current = Environment.CurrentDirectory;
      var probe = Path.Combine("FFmpeg", "bin", Environment.Is64BitProcess ? "x64" : "x86");
      var ffmpegBinaryPath = Path.Combine(current, probe);
      Console.WriteLine(Environment.CurrentDirectory);
      Console.WriteLine($"FFmpeg binaries found in: {ffmpegBinaryPath}");
      DynamicallyLoadedBindings.LibrariesPath = ffmpegBinaryPath;
      DynamicallyLoadedBindings.Initialize();
    
      Console.WriteLine($"FFmpeg version info: {ffmpeg.av_version_info()}");
    var audioService = new FFmpegAudioService();
    var hashedFingerprints = await FingerprintCommandBuilder.Instance
                                     .BuildFingerprintCommand()
                                     .From("c:\\temp\\chopin_short.wav")
                                     .UsingServices(audioService)
                                     .Hash();
    Console.WriteLine(hashedFingerprints.ToString());
```
