### ISSUE TITLE
Docker persistent storage after reboot

### ISSUE THREAD

**Issue by Serek16** [AddictedCS/soundfingerprinting#216]
Hi, I can save tracks to Emy Community storage with Docker and it stays persistent when I re-run the app or docker container but when I restart my computer tracks inside the db are gone.
I'm on Windows 11. To install the container I used `docker run -d -v /persistent-dir:/app/data -p 3399:3399 -p 3340:3340 addictedcs/soundfingerprinting.emy:latest`. I use windows docker desktop app to start and stop container.

**Comment by AddictedCS** [comment]
It's difficult for me to debug your environment, but are you starting and stopping using `start`, `stop` docker commands? Also, when you start the container are you seeing files in your `/persistent-dir` directory?

**Comment by Serek16** [comment]
When the container is running I do have files that resamble my addeed tracks. It's inside /app/data/sfdata/trackRef_x.bin. To start/stop I usually use UI star/stop buttons but for commands is the same. When I stop container files are gone and are back again after I start container again. After I reboot computer and start container files are gone.

**Comment by AddictedCS** [comment]
The path that you've mentioned `/app/data/sfdata/` is inside docker container. You should be looking for the files on your host machine inside `/persistent-dir` or whatever you've specified during run command. To exemplify if you specify `c:/temp:/app/data` then you should be able to see the files in `c:/temp` on your host.

**Comment by Serek16** [comment]
Alright, thanks for clarifying. Don't have much experience with Docker. It works with `c:/temp:/app/data`
