### ISSUE TITLE
Possibility to pass pitch percentage when querying

### ISSUE THREAD

**Issue by christophdebaene** [AddictedCS/soundfingerprinting#217]
DJ mixes are using pitch control so that in some cases it is not recognized.
Is there a possibility that for example in the `QueryCommandBuilder` you can pass a positive or negative pitch percentage?

**Comment by AddictedCS** [comment]
To recognize pitch change, you will have to insert tracks with changed pitch alongside the original.
The algorithm has to have both versions to differentiate (and successfully match the two).
Same stands for tempo change.

**Comment by christophdebaene** [comment]
Let's say a track that is pitched with +4%. 
If you would convert the track to pitch it down again with -4% with `ffmpeg` and `atempo` would that work to recorgnize it as the original, or will it result in a different fingerprint?

**Comment by AddictedCS** [comment]
A pitched changed track will result in different fingerprints and those will match only with pitched changed query. From fingerprints perspective the original and pitched changed tracks are two different tracks.

**Comment by christophdebaene** [comment]
Ok thank you very much for your explanation
