### ISSUE TITLE
Sample rate not supported even when using a .wav with 44.1khz sample rate

### ISSUE THREAD

**Issue by mevansAI** [AddictedCS/soundfingerprinting#220]
**Describe the bug**
When trying to load a sample I get this error.
```
An unhandled exception has occurred while executing the request.
      System.ArgumentException: Sample rate of the given file is not supported Format: SampleRate $544546930, Channels $8313, BitsPerSample $8289, Length $3367674. Supported sample rates 5512,8000,11025,16000,22050,44100,48000,96000. Submit a github request if you need a different sample rate to be supported.
```

I am using a .wav file with a sample rate of 44.1khz so I don't know why its complaining about the file type.

Here is the code snippet I'm using

```
IAudioService audioService = new SoundFingerprintingAudioService(); 
var avReferenceHashes = await FingerprintCommandBuilder
    .Instance
    .BuildFingerprintCommand()
    .From("wavs/rumble2.wav")
    .UsingServices(audioService)
    .Hash();

Console.WriteLine($"Generate hashes {avReferenceHashes}");
```

**Comment by satpal123** [comment]
Maybe try re-encoding it and test again?

**Comment by mevansAI** [comment]
Ah it looks like it works with other files but was having issues with ones I was exporting specifically from Ableton. Not sure why it has issues with .wavs rendered by ableton but re-encoding the file with ffmpeg seemed to do the trick.

Here's the settings I used when exporting my file to a .wav for reference.
<img width="276" alt="Screenshot 2024-03-12 at 3 05 51 pm" src="https://github.com/AddictedCS/soundfingerprinting/assets/109490330/90e901ba-c8d3-4789-b8b1-cf27ad765b34">
