### ISSUE TITLE
Mobile app use?

### ISSUE THREAD

**Issue by Simon-BioMedical** [AddictedCS/soundfingerprinting#224]
Hi, 
Just a quick question - I have used your module within a .NET Core app and it works well.
I have now been asked to integrate this into a React Native Android/iOS app. Do you have a version of this code (either open source, or available to purchase) that is compatible either with RN, or could be compiled as a native Android/iOS resource that we could embed?

Note that I've managed to build it as a MAUI app for testing but I need to get this into an existing RN app.

Many thanks,

Simon.

**Comment by AddictedCS** [comment]
No, there is no port of RN or Android/iOS.

Some have tried using Blazor for similar tasks, as it allows referencing .NET standard libraries even for client-side code.
