### ISSUE TITLE
TrackMatchLengthEntryFilter

### ISSUE THREAD

**Issue by mbonda** [AddictedCS/soundfingerprinting#228]
TrackMatchLengthEntryFilter  can`t found

**Comment by AddictedCS** [comment]
**Breaking Changes:**
`TrackMatchLengthEntryFilter` can be used as `TrackCoverageLengthEntryFilter(waitTillCompletion: false)`
`OngoingRealtimeResultEntryFilter(x, y)` can be chained as new ChainedRealtimeEntryFilter([new TrackRelativeCoverageEntryFilter(x, waitTillCompletion: false), new TrackCoverageLengthEntryFilter(y, waitTillCompletion: false)`])
`TrackRelativeCoverageLengthEntryFilter` can be used as `TrackRelativeCoverageEntryFilter(waitTillCompletion: true)`.
