### ISSUE TITLE
Error running build.cmd

### ISSUE THREAD

**Issue by zecarlosalmeida** [AddictedCS/soundfingerprinting#43]
Hi.
I'm trying to run the build.cmd but ends with the following error:

>D:\Documentos\soundfingerprinting-master\build\Build.proj(33,2): error MSB3073: O comand
 o "..\tools\MSTest.exe /testcontainer:Release\UnitTests\SoundFingerprinting.Tests.dll" concluiu com o código -532462766.

What can be the reason?
My system is windows 8.1 x64.

Thanks and sorry by the poor english.

**Comment by AddictedCS** [comment]
Build.cmd executes all tests for all sub-modules (including MongoDB and MSSQL). Did you start Mongo instance as well as MSSQL on the target system? Also, do you have enough memory RAM?

**Comment by zecarlosalmeida** [comment]
I don't have istalled MongoDB or MSSQL. I have to install both to run? 
My free RAM its about 6Gb.

**Comment by AddictedCS** [comment]
I would recommend you using nuget package directly https://www.nuget.org/packages/SoundFingerprinting.
