### ISSUE TITLE
Attempting to test audio fingerprinting using v2

### ISSUE THREAD

**Issue by computamike** [AddictedCS/soundfingerprinting#49]
Unsure how to test v2 of this library.  I attempted to test using the Nuget version, but that seems to be 1.0.1

How do I use version 2.0?

--  Just realised that the github code trunk is currently at version 2...

**Comment by AddictedCS** [comment]
You can use the -Pre flag when installing the library from the NuGet. It will pull alpha version of the framework 2.0.0.
