### ISSUE TITLE
suggestion : replace 3 doors down (Kryptonite) with Open Source track

### ISSUE THREAD

**Issue by computamike** [AddictedCS/soundfingerprinting#50]
A variety of songs can be downloaded from http://incompetech.com/.  The songs are available under a creative commons licence : http://incompetech.com/music/royalty-free/licenses/

I would suggest that adding a note to the readme.md file would be sufficient to attribute the songs.

I'd suggest going to http://incompetech.com/music/royalty-free/ and using the search tools to pick a song to include.

**Comment by AddictedCS** [comment]
Thanks! 

Thats indeed a valuable advice. I will replace it in the near future.

**Comment by AddictedCS** [comment]
Changed to https://musopen.org/music/2629/frederic-chopin/nocturne-in-c-minor-b-108/
