### ISSUE TITLE
Audio matching from smartphone records

### ISSUE THREAD

**Issue by XavierQuincieux** [AddictedCS/soundfingerprinting#52]
Hi,

I tried to use your library to build a "Shazam like" app for myself. Only for testing purpose, I recorded an audio sample with my smartphone, imported it on my computer and query the database with it.

Unfortunately, with the default configurations, I never get a correct matching of the song. The record is not too bad, there's no significant noise since it was recorded at home in a quiet room from my main speakers system.

Still, default configurations work great to find songs duplicates, so I'm just wondering if there's any configuration parameter that can be specifically tune to reach my goal.

Thanks

Xavier Q.

**Comment by versatgrant** [comment]
What compiler did you use to open the solution file. I tried VC#10 but said it was of a later build.

**Comment by gaborp** [comment]
Hi, I'm facing the same problem. 
Did you manage to tune parameters to achieve better recognition rate on recordings?
Thanks
PG

**Comment by versatgrant** [comment]
Hey,
It works with latest version of visual studio, and no, I've yet to try to alter the parameters from the default ones given.
Thanks,
N.G.

**Comment by AddictedCS** [comment]
Hi @versatgrant,

I've altered the default parameters starting from v.2.1.x. Have you tried those?

Regards, C.S.

**Comment by AddictedCS** [comment]
Version 3.0.0 comes with improved recognition/recall rate. This issue has to be solved now.
