### ISSUE TITLE
Error running build.cmd

### ISSUE THREAD

**Issue by versatgrant** [AddictedCS/soundfingerprinting#55]
HI,

I'm trying to run the build.cmd on a Windows 10 x64 bit OS but ends with the following error #43 :

Build FAILED.

```
->   "C:\Users\Nicola\Documents\GitHub\AddictedCS-soundfingerprinting-890f657\build\Build.proj" (All target) (1) ->
   "C:\Users\Nicola\Documents\GitHub\AddictedCS-soundfingerprinting-890f657\src\SoundFingerprinting.sln" (default target) (2) ->
   "C:\Users\Nicola\Documents\GitHub\AddictedCS-soundfingerprinting-890f657\src\SoundFingerprinting.Audio.NAudio.Test\SoundFingerprinting.Audio.NAudio.Test.csproj" (default target) (9) ->
   (ResolveAssemblyReferences target) -> 

     C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1605,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference: 
```

"C:\Users\Nicola\Documents\GitHub\AddictedCS-soundfingerprinting-890f657\src\SoundFingerprinting.Tests\bin\Release\SoundFingerprinting.Tests.dll", "x86". 

This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project. [C:\Users\Nicola\Documents\GitHub\AddictedCS-soundfingerprinting-890f657\src\SoundFingerprinting.Audio.NAudio.Test\SoundFingerprinting.Audio.NAudio.Test.csproj]

```
   "C:\Users\Nicola\Documents\GitHub\AddictedCS-soundfingerprinting-890f657\build\Build.proj" (All target) (1) ->
   (RunSoundFingerprintingLibTests target) -> 
     C:\Users\Nicola\Documents\GitHub\AddictedCS-soundfingerprinting-890f657\build\Build.proj(28,2): error MSB3073: The command "..\tools\MSTest.exe /testcontainer:Release\UnitTests\SoundFingerprinting.Tests.dll" exited with code -532462766.

1 Warning(s)
1 Error(s)
```

I've attached the [msbuild.log](https://github.com/AddictedCS/soundfingerprinting/files/136612/msbuild.txt) file that was generated from the the running the build.cmd. (Had to convert to .txt to upload)
Please Help.

**Comment by AddictedCS** [comment]
Fixed, by migrating to NUnit 3 and getting rid of managed libraries (i.e. FFTW).
