### ISSUE TITLE
NaudioSourceReader.SeekToSecondInCaseIfRequired not working properly on stereo channels

### ISSUE THREAD

**Issue by gaborp** [AddictedCS/soundfingerprinting#56]
I spotted issue while I was performing recognition of played songs on internet radio stream recording. 
In case when fingerprint recognition was done on original recording (128kbps / 44,1kBps / 2ch) detected song duration was approximately two times longer as actual song in recorded file. Also only half of recording file was analyzed. 
When performing recognition tests on recorded file which was transcoded in mono channel recognition tests were OK.
I solved the problem with modification in method SeekToSecondInCaseIfRequired in NaudioSourceReader as shown below:

```
private void SeekToSecondInCaseIfRequired(int startAtSecond, WaveStream stream)
{
  if (startAtSecond > 0)
  {
    // Original code
    // int actualSampleRate = stream.WaveFormat.SampleRate;
    // int bitsPerSample = stream.WaveFormat.BitsPerSample;
    // stream.Seek(actualSampleRate * bitsPerSample / 8 * startAtSecond, System.IO.SeekOrigin.Begin);

    // Code that fixed the problem
    stream.CurrentTime = stream.CurrentTime.Add(new System.TimeSpan(0, 0, 0, startAtSecond, 0));
  }
}
```

Now I’m getting equal results regardless how many audio channels are present in file being analyzed.

**Comment by AddictedCS** [comment]
Not relevant anymore.
