### ISSUE TITLE
Issue with SoundFingerprinting audio fingerprint builder

### ISSUE THREAD

**Issue by sedestrian** [AddictedCS/soundfingerprinting#57]
Hi i tried to use the library, i'm using the latest version on nuget and i'm having an issue with this code:

var hashedFingerprints = fingerprintCommandBuilder.BuildFingerprintCommand().From(pathToFile).UsingServices(service).Hash().Result;

Where it gives me this error:

Reference to type 'AudioSamples' claims it is defined in 'SoundFingerprinting.Audio', but it could not be found

Is it an error in the library or is it my code?

(If it helps it doesn't give the error until i add the pathToFile variable which is a string variable to the .From() method )

Thanks

**Comment by AddictedCS** [comment]
Its been an issue with the versioning. Lately an effort was put to solve these. All libraries and dependencies has been aligned to v2.3.1 (available on NuGet).
