### ISSUE TITLE
MediaFoundationReader locks the audio file

### ISSUE THREAD

**Issue by night-dog** [AddictedCS/soundfingerprinting#63]
In the internal class NAudioFactory there is a method called GetStream(string pathToAudioFile). 
It creates and returns MediaFoundationReader object:  
`public WaveStream GetStream(string pathToAudioFile)
         {
             return new MediaFoundationReader(pathToAudioFile);
        }`

This MediaFoundationReader class however locks the file which is specified in its constructor. This is a simple test code which demonstrates the problem. 

`           string pathToFile = @"..\AudioSample2.mp3";

            using (WaveStream rdr = new MediaFoundationReader(pathToFile))
               {}
                using (Stream str = new FileStream(pathToFile, FileMode.Open, FileAccess.Read, FileShare.None))
                {}`

This code fails with Access denied exception. In order unlock the file - Reader settings object must be passed to the constructor: 
`new MediaFoundationReader(pathToFile, new MediaFoundationReader.MediaFoundationReaderSettings() { SingleReaderObject = true })`

I've tried to overwrite the same file but it didn't allowed me to. I'm not sure this will be a problem, since I'll use different name of the audio file every time, but having COM objects to lock files like this doesn't seem right. 

Regards, 
Vladimir

**Comment by AddictedCS** [comment]
Why would you want to access the file while it's fingerprinted?

**Comment by night-dog** [comment]
I'm using a asp.net website with a service, which is responsible to analyze the uploaded files. The user uploads this file through the service and it stores it in a folder called "Upload". After this, the service is using the fingerprinting module to find the best match. However if the user uploads the same file twice - it throws access denied exception. I can use workaround and give the uploaded file unique name, something with guid or a date.  But I feel worried because of the fact that the website holds locks to physical files and denying access to them. Do know if the NAudio "com" component used for scanning keeps an open stream to that file? I wonder why the lock is held since the scan operation is completed.  Won't this lead to a memory leak? What will happen if there are hundreds or thousands of files uploaded and for every file there is a lock and probably an open stream?

**Comment by AddictedCS** [comment]
The lock is hold only during a very short timeframe, during which the file is read and resampled.  
It is released once it hits the closing `using` block.
```csharp
 using (var resampler = naudioFactory.GetResampler(stream, sampleRate, Mono))
                {
                    var waveToSampleProvider = new WaveToSampleProvider(resampler);
                    return samplesAggregator.ReadSamplesFromSource(new NAudioSamplesProviderAdapter(waveToSampleProvider), secondsToRead, sampleRate);
                }```
You need to prevent double submission in your app rather than try workarounds.
