### ISSUE TITLE
Problems with Solr

### ISSUE THREAD

**Issue by Dickal** [AddictedCS/soundfingerprinting#69]
Hi. I use Solr Database. I added over 50 000 songs. Database size ~15Gb.
My problems.
When I start solr server, Log:

![1](https://cloud.githubusercontent.com/assets/25767431/22926025/98cf2e62-f2b3-11e6-8ca7-6c33930bc63a.png)

Then I use method GetBestMatchForSong(...)
Log: 

![2](https://cloud.githubusercontent.com/assets/25767431/22926030/9dfaaede-f2b3-11e6-8ec0-e80ff6387515.png)

And MyApp exception that server return error 500.

Do you have any ideas?
Thanks.

**Comment by AddictedCS** [comment]
You have to scale your system by using multiple Solr instances or just pumping more RAM into your current one (which is not a sustainable solution really). Scaling Solr is a way to go.

**Comment by itkingdom** [comment]
Hi,

Do you have experience about this?
We can divide DB into small chunk, each chunk located in separated server, and we do search the sample from the first server to the last server?

**Comment by Dickal** [comment]
I use Solr for the first time. It's hard for me what to do))
Now I use your MSSQL.
And I saw that your method "InsertHashDataForTrack" is slow, because it calls sql procedure in foreach.
I rewrite procedure for receive a DataTable. Build DataTable with fingerprints in c# and call this once.
It's faster >2x.
Need code ?

**Comment by AddictedCS** [comment]
@Dickal whatever improvements you want to share are welcome. You can do so by issuing pull requests.
