### ISSUE TITLE
c# Audio FingerPrint

### ISSUE THREAD

**Issue by AthiVarathan** [AddictedCS/soundfingerprinting#70]
Hi,
I have created winfrom application with mysql database. In that, i want to generate Audio fingerprint and store to the database. Am new to this , So please  explain how to **generate Audio fingerprint** from the file location. 

Thanks in Advance.

**Comment by AddictedCS** [comment]
You can find details of how to create fingerprints from files on the [main](https://github.com/AddictedCS/soundfingerprinting) page of the project.

**Comment by lizzethZaragoza** [comment]
i need to save fingerprints in my db , but i can't install SoundFingerprinting.MySQL , any solution?
