### ISSUE TITLE
Sound Fingerprint - matching track count  and Multiple single track

### ISSUE THREAD

**Issue by AthiVarathan** [AddictedCS/soundfingerprinting#71]
Hi ,

I have using Audio soundfingerprint algorithm, with SQL database which you are providing script and class files. it will get the result the best match song, but it will return only 25 records,  actually matching file more than 25 records. Also Single track matching multiple time how to find that records.

Thank In Advance.

**Comment by AddictedCS** [comment]
`QueryConfiguration` allows you to set `MaxTracksToReturn`.
