### ISSUE TITLE
How to detect Starting and Ending Audio Position with in big file

### ISSUE THREAD

**Issue by janakaprasadab** [AddictedCS/soundfingerprinting#72]
Hi I wanted to detect the Start and ending time of a Audio Feed which is on a bigger Audio files.. Say you play a particular smaller audio clip multiple times.. and I have a audio record for whole show.. We need to find the Occurrence of each play..

**Comment by AddictedCS** [comment]
You can iterate over the result set and analyze all the returning entries.
Every ResultEntry object will contain the following information:

QueryMatchLength - returns how many query seconds matched the resulting track
QueryMatchStartsAt - returns time position where resulting track started to match in the query
TrackMatchStartsAt - returns time position where the query started to match in the resulting track
TrackStartsAt - returns an approximation where does the matched track starts, always relative to the query
