### ISSUE TITLE
Generate 1 snapshot per track

### ISSUE THREAD

**Issue by mtdman** [AddictedCS/soundfingerprinting#76]
In currently version it s possible to persist all fingerprints in one file and do a load to initiate an analysis.
It would be interesting to be able to generate one file for each track and load all files from a directory. This facilitates the maintenance and distribution of fingerprint.

**Comment by AddictedCS** [comment]
Please use SoundFingerprinting.Emy storage. More details here: https://hub.docker.com/repository/docker/addictedcs/soundfingerprinting.emy
