### ISSUE TITLE
Dependancy Injection in Azure Functions

### ISSUE THREAD

**Issue by Reptarsrage** [AddictedCS/soundfingerprinting#78]
```
Exception while executing function: One or more errors occurred. (The type initializer for 'SoundFingerprinting.Infrastructure.DependencyResolver' threw an exception.). SoundFingerprinting.Solr: The type initializer for 'SoundFingerprinting.Infrastructure.DependencyResolver' threw an exception. System.Private.CoreLib: Unable to load one or more of the requested types. 
```
This Exception occurs  whenever I try and run the function. I can trigger DI for my own managed types by biding them myself, statically. However, most of the types in this library are sealed/internal so I cannot resolve this issue.

Making the DependancyResolver/IDependancyResolver publicly accessible so I can rebind them would solve this issue.

**Comment by AddictedCS** [comment]
I assume making `DependancyResolver` public won't solve the issue unless all the classes that are bind during `AppDomain` initialization will be made public as well.

**Comment by AddictedCS** [comment]
I'm now assessing the option of getting rid of Ninject altogether. It's a relic of the past and may not be required in future releases.

**Comment by AddictedCS** [comment]
I will soon release a beta version with Ninject removed, stay tuned.

**Comment by AddictedCS** [comment]
@Reptarsrage check out new version 4.1.0 it comes with improvements and no more Ninject dependency in SoundFingerprinting core library.
