### ISSUE TITLE
Short simple sounds detecting

### ISSUE THREAD

**Issue by Qndzia** [AddictedCS/soundfingerprinting#79]
Is it possible to detect a short simple sounds (like microwave bell, doorbell, ambulance signal) with this soundfingerprinting algorithm?

**Comment by AddictedCS** [comment]
It depends. Generally speaking, all sounds that are in 300-2000 Hz frequency range will be recognized. This range is well suited for audio that contains human voice. Signals that you've mentioned can lie outside of this range and won't be detected.
