### ISSUE TITLE
Track comparison with in specific time  

### ISSUE THREAD

**Issue by Mahadevan9127** [AddictedCS/soundfingerprinting#80]
how can i modify the program for the specific start time and end time without reading entire file. actually i need to modify the program for reading and comparing with specified start time and end time..but, actually the file reads completely and then only its comparing the parameter specified.how can i modify the code for specific read start time and end time without reading it fully?

**Comment by AddictedCS** [comment]
You can specify the `startAt` and `seconds` parameters, during both fingerprinting and query time.
```
// query the underlying database for similar audio sub-fingerprints
 var queryResult = queryCommandBuilder.BuildQueryCommand()
                                         .From(queryAudioFile, secondsToAnalyze, startAtSecond)
                                         .UsingServices(modelService, audioService)
                                         .Query()
                                         .Result;
```
