### ISSUE TITLE
Custom identifier for track

### ISSUE THREAD

**Issue by Nekromancer** [AddictedCS/soundfingerprinting#82]
I'm wondering if there is a chance to have a custom identifier to work with external track database? For example: i have sql database with track info. Every track have it's identifier (long int). I'd love to use this long to identify track from query (i don't really need any of other info in `TrackData`. 

I guess what would be the best for me is api like:
`modelService.InsertHashDataForTrack(<track_id_as_long>, trackReference);`

Now i'm using ISRC field, but it's kinda hack and i'd love to keep database as small as possible (to store only identifier of track, without isrc, artist, title etc.) because i have over 120k tracks to store.

**Comment by AddictedCS** [comment]
Have you tried using a raw `ModelReference<long>`?

```
var trackReference = new ModelReference<long>(value);
modelService.InsertHashDataForTrack(hashDatas, trackReference);
```

**Comment by Nekromancer** [comment]
Thanks for reply. Did you consider possibility to control amount of data you store for track? In my case i think it would save a lot of space if i could get rid of unnecessary data in database. 

For now i'm using other music recognition algorithm (echoprint) but it pretty much fails to recognize ads in radio stream, so i'm looking for an anternative. We have 120k track in our store, and as far as i can tell (i looked around your code) you store much more data for track than i store for echoprint to work. I'm using LMDB database with fingerprints stored as bytes without any overhead at all. And still - LMDB database is 23 GB large right now. So i'm worried about size of your database with so much data in it
