### ISSUE TITLE
Inconsistent result for samples from same song at different times

### ISSUE THREAD

**Issue by VishnuMNair** [AddictedCS/soundfingerprinting#83]
Hi,

I'm trying to directly capture audio samples from speaker line and identify the song playing.
I'm able to identify the song some times 5/100 times. Remaining times it will return some other random song from db.
i'm capturing 5 sec samples at 5512 Hz.
Tried HighprecisionConfiguration also, still no luck.

Thanks in advance!!

**Comment by Nekromancer** [comment]
Have you tried capturing longer samples? In my experience it's really hard to recognize such small samples, it's just not enough information for the algorithm to work on

**Comment by AddictedCS** [comment]
Hey Vishnu,

There are dozen of reason why your samples  may get false positive results.

How many tracks you have in the database?You may want to try using a different frequency range or increase the query threshold if you are tunning towards precision at the expense of the recall? Did you review the Confidence and Coverage values in the query result? What are those values? How did you capture the audio? Is it just ambient noise or audio degradations added as well? Is it stored with metadata included (sample rate, mono/stereo, bit rate)? Is it wave, mp3? What audio service are you using? 
How did you store the initial track? Was it from mp3 or wave? What configuration did you use for insertion (the configs have to match with the one you are using during query)? What version of the library are you using? Can you paste the code for insertion and query?

5 seconds is enough for a reasonably good quality recording. The high precision config was tuned for MIREX dataset achieving 70% recognition rate, but may be not applicable for your use case.

**Comment by VishnuMNair** [comment]
How many tracks you have in the database?
**we have around 75 tracks in database**
You may want to try using a different frequency range or increase the query threshold if you are tunning towards precision at the expense of the recall? 
**I'm not sure about this**
Did you review the Confidence and Coverage values in the query result? What are those values?
**i'm getting confidence as zero even for right results**
How did you capture the audio? 
**We are using bass dll for capturing the audio**
Is it just ambient noise or audio degradations added as well? 
**Yes noise is added due to multiple harness connections**
Is it stored with metadata included (sample rate, mono/stereo, bit rate)?
**No these data is added with song, i'm not aware how to do this** 
Is it wave, mp3?
**database includes both kind of files**
 What audio service are you using?
**we are using NAudio**
How did you store the initial track? Was it from mp3 or wave? What configuration did you use for insertion (the configs have to match with the one you are using during query)? What version of the library are you using? Can you paste the code for insertion and query?
**Initial song was wave file**
**Default config is used in both cases**
**We are using 2.1.0 since we have mysql dependancy**
`  /// <summary>
        /// Store audio file to storage
        /// </summary>
        /// <param name="pathToAudioFile"></param>
        public void StoreAudioFileFingerprintsInStorageForLaterRetrieval(string pathToAudioFile)
        {
            var track = new TrackData("GBBKS1200164", "Adele", "Skyfall", "Skyfall", 2012, 290);

            // store track metadata in the datasource
            var trackReference = modelService.InsertTrack(track);

            // create hashed fingerprints
            var hashedFingerprints = fingerprintCommandBuilder
                                        .BuildFingerprintCommand()
                                        .From(pathToAudioFile)
                                        
                                        .UsingServices(audioService)
                                        .Hash()
                                        .Result;

            // store hashes in the database for later retrieval
            modelService.InsertHashDataForTrack(hashedFingerprints, trackReference);
        }`
for getting match
` /// <summary>
        /// Try getting audio match from Db using samples from Audio tool
        /// </summary>
        /// <param name="samples">Float array of sample collected from audio tool</param>
        /// <param name="sampleRate">rate at which sampling was done</param>
        public TrackData GetMatchForSampleFromDb(float[] samples, int sampleRate)// string pathToSourceFile = @"D:\Junk\Audio1.wav")
        {
            try
            {
                FingerprintConfiguration conf = new HighPrecisionFingerprintConfiguration();
                //Byte[] bytes = File.ReadAllBytes(pathToSourceFile)
                //NAudioSourceReader sourceReader = new NAudioSourceReader();
                //float[] audioSample = sourceReader.ReadMonoFromSource(str, conf.SampleRate, 4, 0);
                //conf.SampleRate = 44100;
                AudioSamples audioSamples = new AudioSamples
                {
                    Samples = samples,
                    Origin = "",
                    SampleRate = conf.SampleRate,
                    Duration = (double)samples.Length / conf.SampleRate
                };
                //FingerprintConfiguration conf = new DefaultFingerprintConfiguration();
                //conf.SampleRate = 44100;
                QueryConfiguration qconf = new HighPrecisionQueryConfiguration();
                // query the underlying database for similar audio sub-fingerprints
                var queryResult = queryCommandBuilder.BuildQueryCommand()
                                                    .From(audioSamples)
                                                    .UsingServices(modelService, audioService)
                                                    .Query()
                                                    .Result;

                return queryResult.BestMatch.Track;
                
            }
            catch (AggregateException ex)
            {
                Exception e = ex.GetBaseException();
                Console.WriteLine(e.Message);
                throw e;
            }
        }`

**Comment by AddictedCS** [comment]
Version 2.1 is an outdated version. Latest 5.1 release comes with tons of improvements including noisy environments handling. You can try it with InMemory model service see if the framework handles the noise and then try to migrate your main app with whatever storage you have. 2.1 was released more than 2 years ago and it is not supported now.
