### ISSUE TITLE
Is length field in TrackData relevant

### ISSUE THREAD

**Issue by Nekromancer** [AddictedCS/soundfingerprinting#85]
Is this field used by algorithm in any way or is it stored only for information on retrieval?

**Comment by AddictedCS** [comment]
Yes, the length field is relevant for `Confidence` and `Coverage` calculation in `QueryResult` data.

**Comment by erick2red** [comment]
> Yes, the length field is relevant for `Confidence` and `Coverage` calculation in `QueryResult` data.

You should add this to the Readme somewhere. I've found an issue where the same files some times match and some don't, and this might be it. After I started adding the proper value there, the issue went away.

**Comment by AddictedCS** [comment]
The `length` will be calculated automatically in the next release v7.1.0. This will be done to remove the confusion related to `Confidence` and `Coverage`.
