### ISSUE TITLE
Problem with silence detection

### ISSUE THREAD

**Issue by DedAnton** [AddictedCS/soundfingerprinting#88]
Hi, I wanted to use your library to detect silence in the record. It works badly. Maybe I should change some settings?

In the rest everything works well, problems arise only with silence.

**Comment by AddictedCS** [comment]
Silence is deliberately removed from the fingerprinted content.

Detecting silence can be done in an easier manner. Just scan the samples from the file and those locations where you have audio samples equal to zeros (or close to zero values) are actual silence.

If let's say you have a mono audio file sampled at 44.1Khz, whenever you find consecutive 44100 sample values equal to 0, you have detected 1 second of silence.

**Comment by DedAnton** [comment]
Everything turned out, thanks!
