### ISSUE TITLE
Track comparison 

### ISSUE THREAD

**Issue by Mahadevan9127** [AddictedCS/soundfingerprinting#95]
Hello sir,
          I have a problem with the track comparison. I am using SQL server for store fingerprints, My database stored more than 20000 tracks. I already run index also, but I am facing performance issue as well as comparison time is more. I need to reduce below two things.
 * Performance.
 * Reduce comparison time.

**Comment by Nekromancer** [comment]
SQL Server is not fit to work with SoundFingerprinting. Storage is already marked as deprecated (and i really doubt that it will change in future. SQL is just not good for this kind of storage). 

Try out Solr. It's working better than SQL in this regard, but still not perfect. If you really want SoundFingerprinting perform best - use in memory storage. RAM is not that expensive nowadays.

Ciumac is already working in database that is tailored for this algorithm. I think it will be the best for your usage. Try to contact him in private mail about alpha access
