### ISSUE TITLE
Internal modifier in TrackData

### ISSUE THREAD

**Issue by Nekromancer** [AddictedCS/soundfingerprinting#98]
I'm attempting to write a simple ModelService based on key-value store.

I found out that in method `IModelReference InsertTrack(TrackData track)` of `ITrackDao` you expect (in tests) that the track will get updated TrackReference. But setter for this property is internal. You worked around this by using `[assembly: InternalsVisibleTo("SoundFingerprinting.Solr")]`, but i have not this luxury. Is it possible to make this setter public (i can make PR for this)? If not - what should i do instead?

**Comment by AddictedCS** [comment]
Will get back to this. Need to take a look on the reasons why I did this.

**Comment by AddictedCS** [comment]
Can you point out to the test which expects what you've mentioned?

The reason why it doesn't have setters is to prevent framework users modifying the fields that are meant to be read-only.

**Comment by Nekromancer** [comment]
Sure. One of these are https://github.com/AddictedCS/soundfingerprinting/blob/develop/src/SoundFingerprinting.Tests/Integration/TrackDaoTest.cs#L40

I get that, but when i'm doing storage i can't modify it without intefering with your code (by adding internalVisibleTo)

**Comment by AddictedCS** [comment]
Not an issue since `v6.0.0` with the modified model service interface.
