### ISSUE TITLE
Storage based on LMDB database

### ISSUE THREAD

**Issue by Nekromancer** [AddictedCS/soundfingerprinting#99]
I managed to create database adapter based on insanely fast key-value store - LMDB. I open sourced it under https://github.com/Nekromancer/SoundFingerprinting.LMDB

It would be great if you could take a look at code and provide any feedback about it.

And if you like it - maybe you could link that in your README? :)

PS. I hope you don't mind - i took some of your integration tests to test out storage.

**Comment by TechnikEmpire** [comment]
If you took some of his tests then you need to carry over his copyright declaration in those tests.

**Comment by AddictedCS** [comment]
Thanks @Nekromancer! Will take a look at this later. I don't me you taking the integration tests. Actually, since there are 3 storages now, I was thinking about releasing a separate DLL just for that.

**Comment by Nekromancer** [comment]
Yes, that would be great :)

**Comment by AddictedCS** [comment]
It's used by the SoundTools https://github.com/AddictedCS/soundfingerprinting.soundtools. It's an internal helper project, built to provide means for analyzing the audio content, fingerprints structure and so on. It's not used by the main framework.

**Comment by Nekromancer** [comment]
Have you considered moving InMemoryStorage out of main library? That would get rid of protobuf dependency, which imho isn't nessesary

**Comment by AddictedCS** [comment]
Hey @Nekromancer, I’ve reviewed the LMDB and here are my thoughts:

- Please re-publish the LMDB under _SoundFingerprinting.Extensions.LMDB_ name. _SoundFingerprinting.*_ prefix is reserved under my NuGet identity name, thus the community expecting me as the author. All extensions written by contributors should be published under _SoundFingerprinting.Extensions.*_ prefix.
- Please, un-list all current _SoundFingerprting.LMDB_ versions, to remove confusion with newly published _SoundFingerprinting.Extensions.LMDB_.
- Consider starting with version 5.2.2.x similar to how other extensions are published. This will make the versioning look consistent, as all extensions are dependent on the core library which drives the version updates.
- You can still upload new versions of LMDB just by updating the last minor version i.e. 5.2.2.**x**.
- In terms of the performance, 50 tracks is not really a use case that I’ve found frequently used. Users normally have at least 500, 1000, thus it would be more interesting to find how the performance looks when this number increases: 50, 100, 500, 1000 will provide a better overview of the dynamics. 
- In case if your target audience is specifically those who need to monitor low number of tracks, you can specify it in the docs.
- Internal modifier for _TrackData_ will stay as it is right now. The whole concept of it getting internally modified was not the best choice I’ve made at a time. There will be changes in the interfaces in the upcoming 6.x version, which will not require any internal modifications.

**Comment by Nekromancer** [comment]
Hey @AddictedCS , thanks for the review.

I will re-publish NuGet to meet these requirements. 

As far as performance goes - right know i'm using this adapter with 3000 ads (so audio samples are usually very small) and 10-20% performance loss (comparing to InMemoryStorage) is still valid in this use case. It would be great it somebody could try this out on larger data set.
